.circleci/config.yml

- Try stretch and python 3.6.8 docker image
- update link to install Miniconda (continuum is now Anaconda, and they provide miniconda3 or miniconda2, which is more explicit than "miniconda")
- Fix pip-caching:
- the pip cache was never restored, because circle only restores the first matching key (see: [here](https://circleci.com/docs/2.0/caching/#restoring-cache)), thus only the data-cache was being restored
- with a second `restore_cache` call, this should be fixed
- I also make the pip-cache contingent on the upstream MNE-Python `environment.yml` ... in case there are changes upstream, we would want to update our cache ...
- lastly: This involved also adding a `pip install -U mne`, because otherwise our cache might make us stuck with an older version of MNE-Python

update conda link, fix pip caching, always upgrade mne

---

Makefile
README.md
config.py

minor changes while I was going through the codebase.
Points I noticed:
- It is unclear how to get the MRI data for the "example" described in the README
- The "example" data on OSF contains an empty `system calibration files` directory in `LocalizerDATA` ... is this an error?

mixed formatting and doc improvements

---

01-import_and_filter.py
02-apply_maxwell_filter.py
03-extract_events.py
04-make_epochs.py
05a-run_ica.py
05b-run_ssp.py
06a-apply_ica.py
06b-apply_ssp.py
07-make_evoked.py
08-group_average_sensors.py
09-sliding_estimator.py
10-time_frequency.py
11-make_forward.py
12-make_cov.py
13-make_inverse.py
14-group_average_source.py
99-make_reports.py
config.py
tests/download_test_data.py

closes #44 
We agreed that it's currently low priority to have a  `make clean` and to not overwrite existing files.
But in #44 the point was raised by @jasmainak that we should not save to `/derivatives` but rather to `derivatives/pipeline-name`.
This is what I do in this PR, and it's in accordance with the WIP spec for BIDS derivatives.
I also write a `dataset_description.json` for the pipeline to comply with the WIP BIDS spec

[MRG] compliance with WIP BIDS derivatives spec

---

.circleci/config.yml
.gitignore
08-group_average_sensors.py
config.py
tests/configs/config_ds001810.py
tests/configs/config_eeg_matchingpennies.py

This works thanks to a fix in `mne-python:master` that will be included in 0.19: https://github.com/mne-tools/mne-python/pull/6711
So this PR should probably only be merged after `mne-python` 0.19 has been released?

RF: Do sensor-level group average via mne.grand_average()

---

12-make_cov.py
config.py

<strike>- Shuffle the data before the cross-validation split. This is required to get any meaningful CV results.</strike>
- Extract the data rank from the `info` structure. At least on my  test data this was necessary to get correct results.
<strike>- Logging and documentation improvements</strike>

BF: Extract the data rank from the info structure when estimating noise covariance

---

04-make_epochs.py

The `group_by` parameter used here is intended for sth else (and doesn't work like this); I believe  `picks` is what we want instead!

BF: Fix epochs.plot_image call

---

config.py

The BIDS root directory could previously only be specified using the environment variable `BIDS_ROOT`. However, users told me this is cumbersome and doesn't really align with what they're used to in their daily work. This commit makes it obvious how to specify a BIDS root path
directly in `config.py`. By default, we will continue to use `BIDS_ROOT` environment variable, but it should now be easy for users to change this behavior.
Also raises a `ValueError` now instead of a `RuntimeError` if no BIDS root has been specified, I think this is more appropriate here.
Let me know what you think – haven't added tests yet because I first wanted to hear your thoughts on this one.

MRG: Allow specification of root path in config.py

---

14-group_average_source.py
99-make_reports.py

This analysis step would fail for me if the condition names contains a forward slash. Need to sanitize the generated filenames.

MRG: BF: Sanitize paths in group-average analysis

---

config.py
tests/run_tests.py

This used to only work with our CI tests, but now users can set `MNE_BIDS_STUDY_CONFIG` to an arbitrary pathand use the configuration from that file. Tests were updated to pass the absolute path of the requested test config.
Closes #83.

MRG: ENH: Allow specification of custom config file

---

01-import_and_maxfilter.py
config.py

This also sets `allow_maxfilter=False` by default, as some `mne-bids` reader functions do not support this kwarg and would fail if it is passed.

MRG: BF: Respect config.allow_maxshield when reading raw data

---

01-import_and_maxfilter.py
02-frequency_filter.py
03-extract_events.py
04-make_epochs.py
05a-run_ica.py
05b-run_ssp.py
06a-apply_ica.py
06b-apply_ssp.py
07-make_evoked.py
08-group_average_sensors.py
09-sliding_estimator.py
10-time_frequency.py
11-make_forward.py
12-make_cov.py
13-make_inverse.py
14-group_average_source.py
99-make_reports.py
config.py
tests/configs/config_ds000117.py
tests/configs/config_ds000246.py
tests/configs/config_ds000248.py
tests/configs/config_ds001810.py
tests/configs/config_ds001971.py
tests/configs/config_eeg_matchingpennies.py
tests/configs/config_somato.py

We need to read the `bids_root` from the custom configuration early (and not at the very end of `config.py`, as is currently the case in `master`).
------
It's becoming more and more clear to me that `config.py`'s complexity is slowly getting out of hand and, like @jasmainak said, it's drifting away from what an ordinary user should have to deal with. I would suggest to start treating it more like an ordinary Python module than just a collection of configuration settings (because in fact we're already past this point anyway), and move the bits that we want to be "user-facing" to an example of a custom configuration file. This PR and #84 make it easy to use different custom configurations; and I'm considering adding a small script `run_pipeline.py` to replace the `Makefile` and allow the …

BF: Fixes for using custom config

---

.circleci/config.yml
tests/download_test_data.py

Since https://github.com/OpenNeuroOrg/datalad-service/issues/96 has been resolved, we can now use more than one job for retrieving the datasets via git-annex. This can considerably speed up dataset retrieval.
Closes GH-95.
@agramfort Let's see what CI thinks about this :)

MRG: Speed up dataset retrieval via datalad

---

01-import_and_maxfilter.py
02-frequency_filter.py
03-make_epochs.py
04a-run_ica.py
04b-run_ssp.py
05a-apply_ica.py
05b-apply_ssp.py
06-make_evoked.py
08-sliding_estimator.py
09-time_frequency.py
10-make_forward.py
11-make_cov.py
12-make_inverse.py
13-group_average_source.py
99-make_reports.py
config.py
tests/run_tests.py

The logging isn't really good at the moment: it will inform you _that_ a critical error occurred, but will not provide info about _where_ exactly (which pipeline step, participant, session etc.) That's because the newly-introduced `@failsafe_run` decorator is used like this:
```python
@failsafe_run(on_error=on_error)
def run_maxwell_filter(subject, session=None):
...
```
so it would have to extract the arguments passed to the wrapped function in order to generate a more meaningful log message. To make this easier, I would first want to switch all `run` functions to use keyword-only arguments, and then `failsafe_run` could be defined with defaults for all possible keywords. In case of an error, these can then be passed to `gen_log_message` to generate an informative log message.

Allow continuation after an error (or, optionally, abort the pipeline)

---

01-import_and_maxfilter.py
02-frequency_filter.py
03-make_epochs.py
04a-run_ica.py
04b-run_ssp.py
05a-apply_ica.py
05b-apply_ssp.py
06-make_evoked.py
07-group_average_sensors.py
08-sliding_estimator.py
09-time_frequency.py
10-make_forward.py
11-make_cov.py
12-make_inverse.py
13-group_average_source.py
99-make_reports.py
config.py

Allows specification of the root folder of the derivatives. Currently not meant to be user-settable.
Removes redundant code across the entire pipeline.

ENH: Add config.deriv_root

---

config.py

Empty-room recordings are now automatically excluded from regular analysis, so there's no need to list `emptyroom` as excluded subject anymore.
Also update some more docstrings.

DOC: Rework docstrings; no need to exclude emptyroom

---

.circleci/config.yml
01-import_and_maxfilter.py

- It's good to have
- I need it for empty-room handling
To give you an example: with the `ds000248` dataset, it produces a file:
`sub-01/meg/sub-01_task-audiovisual_run-01_bad_chans.tsv` with the following content:
| Channel  | Reason                                           |
|----------|--------------------------------------------------|
| EEG 053  | pre-existing (before mne-study-template was run) |
| MEG 1032 | auto-noisy                                       |
| MEG 2313 | auto-noisy                                       |
| MEG 2443 | pre-existing (before mne-study-template was run) |

[MRG] ENH: Keep a log of auto-detected bad channels

---

.circleci/config.yml

We currently don't make any use of them, and they were interfering with some of the tests for #114. (This is something we should definitely fix someday, but currently we don't need this functionality.)
I've just commented out the relevant portions of the Circle config, so we can easily re-enable things again.

TESTS: Don't install any X11/3D related packages

---

config.py

This PR moves `config.conditions` up in the config file, such that it now is the very first setting in the `EPOCHING` section, which -- I believe -- makes a lot of sense. Also improves the documentation.

Move "conditions" config setting up, improve documentation

---

13-group_average_source.py

When processing multiple participants in parallel, one could encounter a race condition if multiple processes were trying to write to the MNE configuration file simultaneously. <strike>We now write the required setting only once, at the beginning of the script, before forking any sub-processes.</strike> Also, we don't need to add this configuration setting (`subjects_dir`), since we explicitly pass it to all functions that require it anyway.

[MRG] BF: Don't alter MNE configuration

---

08-sliding_estimator.py
11-make_cov.py

Do not construct custom cross-validation objects anymore.
- Use MNE's default CV strategy while decoding: only pass the number of splits, but otherwise leave everything else to MNE to decide.
- Use MNE's default CV strategy (incl. number of splits) when estimating the noise covariance.
Current user-facing behavior remains unchanged.
I believe the only reason the CV objects were initially created was to allow for shuffling (which MNE does not do by default). Following our discussions in #141 and #73, we explicitly want to **avoid shuffling**: MNE does the right thing for us already. So let's drop the manually created CV objects.

Use MNE's default cross-validation strategies in decoding, noise covariance estimation

---

.circleci/config.yml
05a-apply_ica.py
05b-apply_ssp.py
06-make_evoked.py
07-group_average_sensors.py
09-time_frequency.py
10-make_forward.py
11-make_cov.py
12-make_inverse.py
13-group_average_source.py
99-make_reports.py
tests/run_tests.py

As discussed in https://github.com/mne-tools/mne-bids/issues/454#issuecomment-653858194
This also allows us to use BIDSPath in more (all?) places now when creating paths.
Also cleans up / unifies some naming schemes.
Example derivatives folder after running the study-template on the somato dataset:
```
.
├── dataset_description.json
├── sub-01
│   └── meg
│       ├── sub-01_task-somato_ave.fif
│       ├── sub-01_task-somato_cleaned-epo.fif
│       ├── sub-01_task-somato_cond-somato-event1_inverse-dSPM_hemi-lh.stc
│       ├── sub-01_task-somato_cond-somato-event1_inverse-dSPM_hemi-rh.stc
│       ├── sub-01_task-somato_cond-somato-event1_inverse-dSPM_morph-fsaverage_hemi-lh.stc
│       ├── sub-01_task-somato_cond-somato-event1_inverse-dSPM_morph-fsaverage_hemi-rh.stc
│       ├── …
```

[MRG] Treat grand-averaged data as if coming from "sub-average" & make derivatives naming more consistent

---

.circleci/config.yml
01-import_and_maxfilter.py
99-make_reports.py
config.py

This is currently non-interactive (purely static viz) until we've decided how to best add interactivity.

[MRG] Add viz of auto-noisy segment detection

---

01-import_and_maxfilter.py

`find_bad_channels_maxwell()` now automatically low-pass filters by default, thanks to https://github.com/mne-tools/mne-python/pull/7983

No need to low-pass filter manually before running find_bad_channels_maxwell() anymore

---

01-import_and_maxfilter.py
config.py
tests/configs/config_ds001810.py

For datasets where no digitizer information (i.e., measured sensor locations) are available, users may wish to use the template montage supplied by the manufacturer (or simply calculated according to the 10/20 etc. systems). This PR adds the `eeg_template_montage` configuration setting that allows to use MNE-Python's built-in templates.
-----
IMHO, this again highlights an issue with the current BIDS specification: that it's not allowed to store montage / channel locations in the dataset if the locations are from a template and not actually measured. For the dataset I'm using for testing here, `ds001810`, I had to dig into `*_eeg.json` to find:
```
"CapManufacturer": "Biosemi",
"CapManufacturersModelName": "CAP 64 10/20",
```
and then I had to start searching for the template – …

Add support for applying an EEG template montage

---

.circleci/config.yml
04a-run_ica.py
config.py
tests/configs/config_ds000248_ica.py

We used to **not** reduce dimensionality, and only limit the number of ICs to fit. 
This is an attempt to avoid running ICA on rank-deficient data: we now reduce dimensionality using PCA before the ICA step. We get rid of the option to select how many ICs to fit; the idea being that this can implicitly be controlled using the PCA step. Let's see how this performs and how many ICs it produces. If it turns out we get "too many" ICs (and ICA therefore takes too long / doesn't converge), we should add the previous option back in, in addition to this new one.

MRG, ENH: Conduct dimensionality reduction before ICA

---

scripts/preprocessing/01-import_and_maxfilter.py

We were unnecessarily loading data twice when processing ERP-CORE.
This also makes it such that we only read `info` and not the entire data of the reference run.

Don't load reference run if we're not going to maxfilter anyway

---

config.py
docs/source/settings/preprocessing/maxfilter.md
scripts/preprocessing/01-import_and_maxfilter.py

To support older BIDS datasets.
cc @agramfort

Add back options for specifying Elekta fine-calib and cross-talk files

---

scripts/freesurfer/recon_all.py

Fixes #287
The recon_all main script should not use positional arguments anymore.
The fix was actually quite simple.
@agramfort  I'm not sure whether I should change any of the tests, so please let me know if I need to.

Prevent n_jobs in recon_all to be changed by positional arguments

---

config.py
docs/source/getting_started/install.md
run.py
tests/run_tests.py

We don't test this in CI, so … let's wait for users to complain, I guess ;)
Fixes #288

Make type imports work on Python <3.8

---

tests/configs/config_ds003392.py

The variable specifying which participants to process was incorrectly named.
Closes #284

Tiny update to the Localizer config

---

docs/source/changes.md
scripts/freesurfer/recon_all.py

Turns out that the use of Fire in `recon_all.py`, combined with Fire in `run.py`, created some weird kind of chaining that ended up passing arguments to `recon_all.py` that were supposed to be consumed by `run.py` only.
Since `recon_all.py` has already been somewhat tightly integrated with `run.py` / the BIDS Pipeline, I now simply removed Fire from it, and we get all info we need to operate from the user's Pipeline config and environment variables.
Fixes #295
cc @MerlinDemeur

Fix recon_all script

---

config.py
docs/source/changes.md

minor typo in comment of epochs_metadata_keep_first

minor typo in comment

---

config.py
scripts/freesurfer/recon_all.py
scripts/init/00-init_derivatives_dir.py
scripts/preprocessing/01-import_and_maxfilter.py
scripts/preprocessing/02-frequency_filter.py
scripts/preprocessing/03-make_epochs.py
scripts/preprocessing/04a-run_ica.py
scripts/preprocessing/04b-run_ssp.py
scripts/preprocessing/05a-apply_ica.py
scripts/preprocessing/05b-apply_ssp.py
scripts/preprocessing/06-ptp_reject.py
scripts/report/01-make_reports.py
scripts/sensor/01-make_evoked.py
scripts/sensor/02-sliding_estimator.py
scripts/sensor/03-time_frequency.py
scripts/sensor/04-group_average.py
scripts/source/02-make_forward.py
scripts/source/03-make_cov.py
scripts/source/04-make_inverse.py
scripts/source/05-group_average.py

This ensures that the documentation for both parameters shows up correctly in the rendered output. In `main`, that's not the case, because we re-defined both variables in `config.py` after their first introduction with a corresponding docstring. The re-definition, however, nixes the docstring. The getter functions solve this issue.
No changelog entry needed as only a documentation change to users.

Add getter functions for {bids,deriv}_root

---

docs/source/changes.md
scripts/preprocessing/01-import_and_maxfilter.py

The sanity check comparing the rank of the experimental data and the rank of the empty-room after the maxfilter did not use the maxfiltered matrices
-  [x] Changelog has been updated (`docs/source/changes.md`)

bug in the sanity check after maxfilters.

---

.circleci/config.yml

We need to clear the cache, otherwise the download will continue to fail

Clear ds003392 cache

---

.circleci/config.yml

The squash-docs job was never run, let's see if this fixes
it

Deploy CircleCI config to gh-branches so the job will run

---

config.py
docs/source/features/steps.md
docs/source/getting_started/basic_usage.md

You can probably tell by my flurry of PRs that I love this package! One thing that I have noticed is that to understand what is happening you need to dig in to the code, and I can see this issue is already being discussed in #350. To improve the onboarding of new users I have suggested some more description for the documentation.
I found the package easy to setup and get running. But I had trouble interpreting the `sliding_estimator` section of the report. To me it was unclear what the applied pipeline was and what the plots illustrated. Specifically I was unsure how to interpret the average subject report, I was not sure if the results were simply the mean of the individual results, or if the script was training on a subset of subjects and testing on previously unseen subjects. This may …

Expand sliding window documentation description

---

docs/source/changes.md
scripts/preprocessing/05a-apply_ica.py
tests/configs/config_ERP_CORE.py
tests/configs/config_ds000248_ica.py

Following a discussion with @agramfort, @SophieHerbst and @hoechenberger, there were indeed some inconsistencies between the calculation of the ica and the plotting of the correction of the ica in the short ica report.
See, for this case study, before:
and after:

Reject bad epochs in apply_ica diagnostic plot

---

config.py
docs/source/changes.md
scripts/preprocessing/03-make_epochs.py
scripts/preprocessing/04a-run_ica.py
scripts/sensor/02-sliding_estimator.py
scripts/sensor/03-time_frequency.py
scripts/sensor/04-group_average.py

When `eeg_reference` is a string other than `'average'`, we currently crash
on `main`. This problem was discovered when working with @dnacombo

Fix bug when eeg_reference is a string

---

config.py
scripts/freesurfer/recon_all.py
tests/configs/config_ds000246.py

Didn't work properly before: recon-all output was always written to `SUBJECTS_DIR/`.
Fixes #404

Enforce specification of subjects_dir if deriv_root is set

---

scripts/preprocessing/02-frequency_filter.py

When there is no frequency filter applied to the raw file  (so h_freq=None and l_freq=None) no raw "filt" file is created and it creates a bug at the beginning of "make_epochs" when this file is called.

Bug occuring when l_freq and h_freq = None

---

docs/source/changes.md
run.py
scripts/preprocessing/01-maxfilter.py
scripts/preprocessing/04a-run_ica.py
scripts/preprocessing/04b-run_ssp.py
scripts/preprocessing/05a-apply_ica.py
scripts/preprocessing/05b-apply_ssp.py
scripts/sensor/01-make_evoked.py
scripts/sensor/03-time_frequency.py

We now print "Skipping …" if a step is being skipped, so users can be certain there was no fluke.

Add one line of output if we skip a step

---

config.py
scripts/preprocessing/04b-run_ssp.py

In order to work autoreject needs at least 5 epochs. Here, if there are not enough ecg or eog epochs the rejection threshold is set to None.
I tested it on a few subjects and it seems to work :ok_hand:

Fix error occuring when there are not enough ecg or eog epochs for autoreject

---

config.py
docs/source/changes.md
run.py
scripts/report/_01_make_reports.py

We didn't make use of provided `event_id` when generating events from annotations. This could lead to inconsistent event code <> event name mappings across
runs or participants.

Fix bug in make_epochs()

---

.gitignore
docs/source/changes.md
scripts/preprocessing/_03_make_epochs.py
scripts/preprocessing/_04a_run_ica.py

Peak memory consumption during epoching reduced by more than 50%!
And we're also faster now!
- We preload epochs so we can remove the respective raw from memory
- Instead of creating a list of all epochs for all runs before concatenation and then concatenating them all at once, we now concatenate epochs immediately after they were created. This further reduced peak memory usage significantly (although I don't fully understand why!)
- During ICA epochs generation, we now drop all epochs that are not in `config.conditions`. In `main`, we create epochs from ALL events, often creating uselessly huge numbers of epochs, increasing memory footprint and massively slowing down ICA decomposition.
- We now only keep a max of 300 EOG and ECG epochs (hardcoded limit)
We may be able to further reduce …

Drastically reduce memory usage during epoching

---

requirements.txt
tests/requirements.txt

joblib has some built-in memory leak detection that requires `psutil` to function. I think it therefore makes sense to add `psutil` to our list of dependencies.
https://joblib.readthedocs.io/en/latest/developing.html#release-0-12-2

Add psutil dependency

---

config.py
docs/source/changes.md
docs/source/settings/general.md
scripts/report/_01_make_reports.py

Previously we'd only plot the PSD of raw data for the first run to speed up report generation. Working with @SophieHerbst we discovered that this is not a good choice for us, so this PR:
- changes the default behavior such that we get a PSD plot for each run
- add a new config option, `plot_psd_for_runs`, allowing users to control this behavior
Also, we now add epochs to the report. It appears I simply forgot about them when transitioning to the new MNE Report API.

Add epochs to the report. Add plot_psd_for_runs setting.

---

config.py
scripts/report/_01_make_reports.py

We now have `run_report_preprocessing`, `run_report_sensor`, and `run_report_source`. Should be easier to digest, maintain, and profile!
This is also a step toward resolving #332 (allowing us to produce reports directly after preprocessing)

Split report generation function into smaller entities

---

requirements.txt

Required to get started as tqdm is imported in `mne-bids-pipeline/scripts/sensor/04-group_average.py` so on a fresh install, just running the pipeline crashes immediately. See https://github.com/mne-tools/mne-bids-pipeline/blob/3bd255f390aaabd73c9fa5ac3382a7719a19136f/scripts/sensor/04-group_average.py#L156 as well as the "install.md" file here https://github.com/mne-tools/mne-bids-pipeline/blob/3bd255f390aaabd73c9fa5ac3382a7719a19136f/docs/source/getting_started/install.md
Otherwise we could remove the use of `tqdm` there, I'll let the maintainers decide.

Adds tqdm to the requirements

---

docs/source/changes.md
scripts/report/_01_make_reports.py

Tested source report rendering with some real-world data.
MRI/BEM rendering was sped up by ~80%
Souce-space report became 20% smaller
(still way too big though, but we're slowly getting there!)
```
main:
report size: 114 MB
BEM rendering duration: 49 sec
PR:
report size: 91 MB 
BEM rendering duration: 10 sec
```

Stronger decimation for MRI & BEM plotting

---

scripts/report/_01_make_reports.py

Reports were erroring with `'BunchConst' object has no attribute 'ica_reject'`, presumably following commit e6d7d7a20cfbf099b0ade7ad432dbf482d70db81.
This change straightforwardly pulls `ica_reject` from `config` and adds it to `cfg` in `get_config`.

Adds `ica_reject` to `cfg` during `get_config` in `scripts/report/_01_make_reports.py`, fixes `no attribute` error

---

LICENSE.txt
tests/datasets.py

closes #507 
- I updated the data in https://github.com/bids-standard/bids-examples/pull/265
- I tried pushing to OSF, then noticed that they have a new 5GB limitation, which I exceeded (EDIT: the cap might be [50GB](https://help.osf.io/hc/en-us/articles/360054528874-OSF-Storage-Caps) for *public* repos, maybe this step and the one below occurred in opposite order)
- in the process, [my OSF project](https://osf.io/cj2dr/) got marked as SPAM :-) (meaning they automatically set it to _private_ ... I need to discuss with their support now)
- Now trying to do it via [GIN](https://gin.g-node.org/sappelhoff/eeg_matchingpennies)
- If that doesn't work, I'll upload a small archive to the MNE OSF account as the easiest solution

[tests] update eeg_matchingpennies location

---

scripts/sensor/_01_make_evoked.py

When I renamed that variable to follow `mne`'s name I didn't realize that it clashed with the dict used all over the place in that code block... Sorry about that!

Remove name clash introduced by PR #537

---

config.py
docs/source/changes.md
tests/configs/config_ds000248.py
tests/requirements.txt

fix of typing object for python < 3.9

---

config.py
scripts/preprocessing/_01_maxfilter.py

There was actually a bug hidden somewhere in our run-getting logic!
Fixes #549

Fix log message "Loading reference run: None"

---

config.py
docs/source/changes.md
docs/source/settings/sensor/statistics.md
scripts/report/_01_make_reports.py
scripts/sensor/_03_decoding_time_by_time.py
scripts/sensor/_99_group_average.py
tests/configs/config_ERP_CORE.py

Add generalization across time

---

docs/source/changes.md
scripts/preprocessing/_04a_run_ica.py

Reported on the forum:
https://mne.discourse.group/t/critical-error-mne-bids-pipeline-ica-automated-eog-artefact-correction-on-fp1-and-fp2/

EEG channels couldn't be used as virtual EOG channels

---

.circleci/config.yml
docs/source/changes.md
scripts/preprocessing/_02_frequency_filter.py
tests/datasets.py

Pushing with a `circle full` since we hadn't done it for a while in #563 (whoops!)

DOC: Add to changes

---

docs/source/css/extra.css

Closes #575
@hoechenberger you added this in #543 where I see:
> Reduce table row height in example docs
Do you want to try pushing a different fix that doesn't cause the problem in #575, or just live with this revert?

STY: Fix doc table line height

---

docs/source/changes.md
scripts/source/_02_make_forward.py

`add_dist='patch'` doesn't add much time, but it improves the source space normal definitions by using the average normal in a surface patch (i.e., of all high-res verts for which the given source space vert is the closest source space vert)

BUG: Use patch information in computing normals

---

.circleci/config.yml
config.py
docs/mkdocs.yml
docs/source/changes.md
docs/source/getting_started/freesurfer.md
docs/source/settings/general.md
scripts/preprocessing/_01_maxfilter.py
scripts/preprocessing/_02_frequency_filter.py
scripts/preprocessing/_03_make_epochs.py
scripts/preprocessing/_04a_run_ica.py
scripts/report/_01_make_reports.py
scripts/sensor/_01_make_evoked.py
scripts/sensor/_99_group_average.py
scripts/source/_99_group_average.py
tests/configs/config_ds000247.py
tests/configs/config_ds003775.py
tests/datasets.py
tests/run_tests.py

ok for you @sappelhoff @hoechenberger ?
see at https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html
The task label included in the file name is derived from this "TaskName" field by removing all non-alphanumeric ([a-zA-Z0-9]) characters. For example "TaskName" "faces n-back" will correspond to task label facesnback. A RECOMMENDED convention is to name resting state task using labels beginning with rest.

rest condition should have task name starting with rest not == to rest

---

config.py
docs/source/changes.md
docs/source/settings/preprocessing/ssp_ica.md
scripts/preprocessing/_04b_run_ssp.py
tests/configs/config_ds000248.py

When using maxfiltered data, `meg='combined'` usually makes sense. Maybe we should have this default to `True` meaning "combined when using maxfilter and separate otherwise", but this should maybe be an upstream change first in MNE-Python. In the meantime, let's expose the option at least.

ENH: Add ssp_meg option

---

scripts/preprocessing/_02_frequency_filter.py
tests/configs/config_ds000248.py

If you use maxwell filtering, baseline noise cov, and `process_er=True`, you get an error:
```
File "/home/larsoner/python/mne-bids-pipeline/scripts/preprocessing/_02_frequency_filter.py", line 221, in filter_data
bids_path_noise = in_files["raw_noise"]
KeyError: 'raw_noise'
```
The first commit should hopefully expose this problem (true TDD!). The second should hopefully fix it.
No changelog update necessary I think because it's a within-release fix. This was introduced in #563

BUG: Fix bug with freq filt caching

---

config.py
docs/source/changes.md
run.py
scripts/freesurfer/_02_coreg_surfaces.py
scripts/init/_00_init_derivatives_dir.py
scripts/preprocessing/_01_maxfilter.py
scripts/preprocessing/_02_frequency_filter.py
scripts/preprocessing/_03_make_epochs.py
scripts/preprocessing/_04a_run_ica.py
scripts/preprocessing/_04b_run_ssp.py
scripts/preprocessing/_05a_apply_ica.py
scripts/preprocessing/_05b_apply_ssp.py
scripts/preprocessing/_06_ptp_reject.py
scripts/report/_01_make_reports.py
scripts/sensor/_01_make_evoked.py
scripts/sensor/_02_decoding_full_epochs.py
scripts/sensor/_03_decoding_time_by_time.py
scripts/sensor/_04_time_frequency.py
scripts/sensor/_99_group_average.py
scripts/source/_01_make_bem_surfaces.py
scripts/source/_02_make_forward.py
scripts/source/_03_make_cov.py
scripts/source/_04_make_inverse.py
scripts/source/_99_group_average.py
tests/run_tests.py

ENH: Add --debug to run_tests.py

---

config.py
docs/source/changes.md
run.py
scripts/init/_00_init_derivatives_dir.py
scripts/preprocessing/_01_maxfilter.py
scripts/preprocessing/_02_frequency_filter.py
scripts/preprocessing/_03_make_epochs.py
scripts/preprocessing/_04a_run_ica.py
scripts/preprocessing/_04b_run_ssp.py
scripts/preprocessing/_05a_apply_ica.py
scripts/preprocessing/_05b_apply_ssp.py
scripts/preprocessing/_06_ptp_reject.py
scripts/sensor/_01_make_evoked.py
scripts/sensor/_02_decoding_full_epochs.py
scripts/sensor/_03_decoding_time_by_time.py
scripts/source/_03_make_cov.py
tests/run_tests.py

- Add `.pop` to read steps and `assert len(in_files) == 0` at the end of each step (as in the `make_evoked` step)
- Time frequency
- Report (maybe?)
-  Add re-run test checks on CircleCI... somehow?

ENH: Add more step caches

---

docs/source/examples/gen_examples.py

I have wanted a table showing the capabilities of all examples in one place. This is at least a proof of concept that it can be done. @hoechenberger any interest in taking over to make it more readable? If a sticky first column (via CSS) is good enough I could do that, but thought you might have more ideas.

WIP: Add table with all examples

---

config.py
docs/source/changes.md
run.py
scripts/freesurfer/_02_coreg_surfaces.py
scripts/source/_01_make_bem_surfaces.py
scripts/source/_02_make_forward.py
scripts/source/_03_make_cov.py
tests/configs/config_ds000248.py
tests/configs/config_ds000248_coreg_surfaces.py
tests/run_tests.py

Not super thoroughly tested, but the ideas are there at least.
Questions

ENH: Cache coreg, bem, cov

---

mne_bids_pipeline/scripts/report/_01_make_reports.py
mne_bids_pipeline/scripts/sensor/_04_time_frequency.py

Fixes:
> RuntimeWarning: This filename (.../derivatives/mne-bids-pipeline/sub-007/meg/sub-007_task-whatever_power+condition+tfr.h5) does not conform to MNE naming conventions. All tfr files should end with -tfr.h5 or _tfr.h5
Is using `-tfr` instead of `+tfr` the correct fix here @hoechenberger ? Or do we need to update MNE-Python to be more tolerant here somehow?

BUG: Fix bug with naming

---

docs/source/changes.md
docs/source/settings/general.md
mne_bids_pipeline/config.py
mne_bids_pipeline/scripts/preprocessing/_01_maxfilter.py
mne_bids_pipeline/scripts/preprocessing/_02_frequency_filter.py
mne_bids_pipeline/scripts/preprocessing/_03_make_epochs.py
mne_bids_pipeline/scripts/report/_01_make_reports.py
mne_bids_pipeline/tests/configs/config_ds000248.py
mne_bids_pipeline/tests/configs/config_ds000248_no_mri.py
mne_bids_pipeline/tests/configs/config_ds003392.py
mne_bids_pipeline/tests/configs/config_ds004229.py

The logic and flow seems simpler and more transparent to me now. `noise_cov` is no longer used at all in `maxfilter` or `frequency_filter` steps, which is nice!
Closes #632

MAINT: Cleaner logic for empty-room and rest data

---

.github/workflows/run-tests.yml
Makefile
mne_bids_pipeline/_io.py
mne_bids_pipeline/scripts/init/_01_find_empty_room.py
mne_bids_pipeline/scripts/init/__init__.py
mne_bids_pipeline/scripts/preprocessing/_01_maxfilter.py
mne_bids_pipeline/scripts/preprocessing/_02_frequency_filter.py
pyproject.toml

Not sure if a `changelog.md` is really necessary here since this is mostly for internal account purposes.
Also tests https://github.com/hoechenberger/openneuro-py/pull/75 implicitly. Locally I actually get some failures with `ds000248` when downloading the dataset, I wonder if something is broken. We'll see if CircleCI has the same problem...
Eventually we'll want to add the set of empty-room files MNE-BIDS will look at for empty-room files, but that will require refactoring MNE-BIDS a bit. So for now let's assume that users have a complete dataset (if they want one) from the beginning.
Closes #629

ENH: Add find_empty_room step

---

docs/source/changes.md
mne_bids_pipeline/run.py
mne_bids_pipeline/scripts/preprocessing/_04a_run_ica.py
pyproject.toml

Fixes the oversubscription problem on my machine. I opened https://github.com/dask/dask/issues/9588 for dask. Until they fix it (if they ever do), we can improve things. This code:
```
$ time mne_bids_pipeline --config mne_bids_pipeline/tests/configs/config_ERP_CORE.py --task ERN --steps=preprocessing/_04a_run --cache=0
```
now decreases from 3m17.387s on `main` to 1m7.732s on this PR. I checked, and there seems to be no need to do this for `loky` backend because the `inner_num_threads` must set it properly in `joblib` (or in `sklearn`, not sure).
Also fixes a bug where `--help` could only be detected by `fire.Fire` when it was the only argument. Now if it appears anywhere in the arg list the `--help` is shown.
Closes #626

BUG: Fix bug with oversubscription in ICA on M1

---

docs/source/changes.md
mne_bids_pipeline/scripts/sensor/_03_decoding_time_by_time.py

Closes #570
Unfortunately we can't really get this to work for `dask` -- workers can't write to the host to give updates, and the `memmap` approach that works for joblib does not appear to work for dask -- so there no progress bar is shown. The alternative would be to show a progress bar that doesn't update at all, which seems worse than not showing one in the first place.
Locally if I comment out the `parallel_backend = 'dask'` and use the bugfix branch https://github.com/mne-tools/mne-python/pull/11311, then I get nice updates:
https://user-images.githubusercontent.com/2365790/200845655-80dfae6d-698a-4b6c-938f-5638db749475.mp4

ENH: Show progress for fitting

---

mne_bids_pipeline/run.py
mne_bids_pipeline/scripts/report/_01_make_reports.py
mne_bids_pipeline/tests/run_tests.py
pyproject.toml

This PR proposes to remove `fire` in support of `optparse`. `Fire` has the advantage of automatically turning a function into a command-line util (neat magic!), but I think it comes with several problematic deficiencies:
1. `-h` and `--help` are not autodetected, we needed to work around it.
2. Extra/wrong arguments/switches are not detected properly, we needed to work around it.
3. We have to do a bunch of `str` mangling to deal with the fact that Fire converts stuff like `--subject=123` into an `int`, `optparse` makes this stuff explicit
4. It does not support `store_true`-style switches like just doing `--interactive` to enable interactive mode -- you have to pass `--interactive=1` which is bad/non-standard Unix command-line interfacing
5. `Fire` is nowhere near as standard as …

MAINT: Simplify by removing fire

---

.circleci/config.yml
.github/workflows/release.yml
pyproject.toml

I tried to upload to PyPI and got:
```
Invalid value for requires_dist. Error: Can't have direct dependency: "autoreject @ https://api.github.com/repos/autoreject/autoreject/zipball/master ; extra == 'dev'"
```
It seems that PyPI does not want any requirements to be URL-based, so this PR removes the `dev` target that contained all URL-based `main` requirements.

MAINT: Remove URL-based reqs

---

.circleci/config.yml
.circleci/setup_bash.sh
.github/workflows/run-tests.yml
Makefile
docs/mkdocs.yml
docs/overrides/main.html
docs/source/examples/gen_examples.py
mne_bids_pipeline/_report.py
mne_bids_pipeline/tests/conftest.py
pyproject.toml

My plan is to first build and deploy two versions of the docs (`1.0`/`stable` and `dev`) with:
```
$ rm -rf ~/mne_data/derivatives/mne-bids-pipeline  # clean runs
$ git checkout v1.0.0       # so that the correct version shows up in sys_info in the reports
$ pip install --no-build-isolation -ve .
...
Successfully installed mne-bids-pipeline-1.0.0
$ pytest mne_bids_pipeline --pdb # build all report HTMLs (without dask)
$ git checkout mike         # switch to this PR's branch so docs build with correct dropdowns, etc
$ ./docs/build_docs.sh  # get one clean update
$ ARGS="--config-file docs/mkdocs.yml --remote=upstream"
$ mike delete --all $ARGS
$ mike deploy 1.0 stable --update-aliases $ARGS
$ mike set-default $ARGS stable
$ mike deploy dev $ARGS
$ mike serve $ ARGS  # visual inspection
$ …
```

MAINT: Use mike for doc deployment

---

.circleci/config.yml
README.md
docs/source/v1.0.md.inc

Tags don't run on CircleCI by default, so we need to add it to each job individually (ouch).

BUG: Fix bug with tag deployment

---

.git-blame-ignore-revs
.github/workflows/run-tests.yml
.pre-commit-config.yaml
docs/source/v1.1.md.inc
pyproject.toml

MAINT: Black infra

---

mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/_report.py
mne_bids_pipeline/tests/conftest.py
mne_bids_pipeline/tests/datasets.py
mne_bids_pipeline/tests/test_run.py

closes #715
@apmellot can you see if it fixes your problem?

using caching for get_runs_all_subjects to speed up get_runs

---

mne_bids_pipeline/__init__.py
pyproject.toml

With this change I get `1.2.0.dev4+g12735039.d20230301` instead of `1.1.1.dev4+g12735039.d20230301` as the version (note the proper minor version bump).
Also a tiny change where `__version__` always gets set.
No need for `changelog` update I think since this is a dev-facing change

BUG: Fix bug with dev version numbering

---

docs/mkdocs.yml

Fixes #730
Not sure if we need a changelog entry for this one?

Re-enable the copy button for code blocks in the documentation

---

docs/source/v1.3.md.inc
mne_bids_pipeline/steps/sensor/_99_group_average.py

Always generate grand-averaged CSP decoding results if CSP was used on single-subject level

---

docs/source/v1.3.md.inc
mne_bids_pipeline/_run.py

I think this preserves the original intent: append anything that's new (`mode='a'`) but replace the given sheet name if it exists. `if_sheet_exists` is available as of Pandas 1.3 (July 2021) so it seems fine to use.
Closes #721

MAINT: Dont use deprecated book API

---

.circleci/setup_bash.sh
docs/source/v1.3.md.inc
mne_bids_pipeline/_logging.py
mne_bids_pipeline/_main.py
mne_bids_pipeline/_run.py
mne_bids_pipeline/tests/test_validation.py
mne_bids_pipeline/typing.py
pyproject.toml

For now I tried to keep the styling pretty similar. One immediate advantage is that `rich` autodetects filenames and makes them magenta, which is cool!
Follow-up PRs could use better box drawing, titling/horizontal ruling, etc. I'll leave that to you @hoechenberger :)
Closes #726

MAINT: Use rich instead of coloredlogs

---

docs/source/v1.4.md.inc
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/_import_data.py
mne_bids_pipeline/steps/init/_01_init_derivatives_dir.py
mne_bids_pipeline/steps/init/_02_find_empty_room.py
mne_bids_pipeline/steps/preprocessing/_01_data_quality.py
mne_bids_pipeline/steps/preprocessing/_02_maxfilter.py
mne_bids_pipeline/steps/preprocessing/_03_frequency_filter.py
mne_bids_pipeline/steps/preprocessing/_04_make_epochs.py
mne_bids_pipeline/steps/preprocessing/_05a_run_ica.py
mne_bids_pipeline/steps/preprocessing/_05b_run_ssp.py
mne_bids_pipeline/steps/preprocessing/_06a_apply_ica.py
mne_bids_pipeline/steps/preprocessing/_06b_apply_ssp.py
mne_bids_pipeline/steps/preprocessing/_07_ptp_reject.py
mne_bids_pipeline/steps/sensor/_01_make_evoked.py
mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py
mne_bids_pipeline/steps/sensor/_03_decoding_time_by_time.py
mne_bids_pipeline/steps/sensor/_04_time_frequency.py
mne_bids_pipeline/steps/sensor/_05_decoding_csp.py
mne_bids_pipeline/steps/sensor/_06_make_cov.py
mne_bids_pipeline/steps/sensor/_99_group_average.py
mne_bids_pipeline/steps/source/_04_make_forward.py
mne_bids_pipeline/steps/source/_05_make_inverse.py
mne_bids_pipeline/steps/source/_99_group_average.py
mne_bids_pipeline/tests/conftest.py

I went to work on #574 and the sheer volume of `kwargs` in `get_config` that must be used to `import_*_data` made it really hard to start from one of the `steps/preprocessing/*.py` files to add a new step. This PR is a no-op from the user standpoint but refactors to:
1. `_bids_kwargs` function that returns some standard BIDS kwargs like `cfg.space`. Eventually we should use this everywhere probably but I'm just starting with `steps/preprocessing` for now.
2. `_import_data_kwargs` function that gets the `config` params needed for reading raw data
Should be a lot more red than green here. I don't expect the first version to pass -- locally I've only run `ds004229` -- but hopefully it won't require many more iterations to get right!

MAINT: DRY kwarg passing

---

docs/source/v1.4.md.inc
mne_bids_pipeline/_config.py

Fix for documentation issue related to processing EEG separately in a combined M/EEG dataset

---

docs/source/settings/general.md
docs/source/v1.4.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/_import_data.py
mne_bids_pipeline/_logging.py
mne_bids_pipeline/_main.py
mne_bids_pipeline/_report.py
mne_bids_pipeline/_run.py
mne_bids_pipeline/steps/init/_02_find_empty_room.py
mne_bids_pipeline/steps/preprocessing/_01_data_quality.py
mne_bids_pipeline/steps/preprocessing/_02_head_pos.py
mne_bids_pipeline/steps/preprocessing/_03_maxfilter.py
mne_bids_pipeline/steps/preprocessing/_04_frequency_filter.py
mne_bids_pipeline/tests/configs/config_ds000117.py

Should be a no-op. Will push commits periodically to check that everything still works and ping when ready for review.

MAINT: Refactor _get_raw_paths

---

docs/source/settings/preprocessing/maxfilter.md
docs/source/v1.5.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_report.py
mne_bids_pipeline/steps/preprocessing/_03_maxfilter.py
mne_bids_pipeline/tests/configs/config_ds004229.py

With updated vals for `ds004229`:
```
mf_mc_rotation_velocity_limit = 30.0  # deg/s for annotations
mf_mc_translation_velocity_limit = 20e-3  # m/s
```
During the run we see:
```
[14:47:31] │ ⏳️ preprocessing/_03_maxfilter sub-102 Translation velocity exceeded 0.02 m/s limit for 5.5 s (1.8%)
[14:47:31] │ ⏳️ preprocessing/_03_maxfilter sub-102 Rotation velocity exceeded 30.0 °/s limit for 4.0 s (1.3%)
```
And in the report we get:

ENH: Add annotation of head velocity

---

docs/source/v1.5.md.inc
mne_bids_pipeline/_run.py
mne_bids_pipeline/steps/freesurfer/_02_coreg_surfaces.py
mne_bids_pipeline/steps/init/_02_find_empty_room.py
mne_bids_pipeline/steps/preprocessing/_01_data_quality.py
mne_bids_pipeline/steps/preprocessing/_02_head_pos.py
mne_bids_pipeline/steps/preprocessing/_03_maxfilter.py
mne_bids_pipeline/steps/preprocessing/_04_frequency_filter.py
mne_bids_pipeline/steps/preprocessing/_05_make_epochs.py
mne_bids_pipeline/steps/preprocessing/_06a_run_ica.py
mne_bids_pipeline/steps/preprocessing/_06b_run_ssp.py
mne_bids_pipeline/steps/preprocessing/_07a_apply_ica.py
mne_bids_pipeline/steps/preprocessing/_07b_apply_ssp.py
mne_bids_pipeline/steps/preprocessing/_08_ptp_reject.py
mne_bids_pipeline/steps/sensor/_01_make_evoked.py
mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py
mne_bids_pipeline/steps/sensor/_03_decoding_time_by_time.py
mne_bids_pipeline/steps/sensor/_04_time_frequency.py
mne_bids_pipeline/steps/sensor/_05_decoding_csp.py
mne_bids_pipeline/steps/sensor/_06_make_cov.py
mne_bids_pipeline/steps/source/_01_make_bem_surfaces.py
mne_bids_pipeline/steps/source/_02_make_bem_solution.py
mne_bids_pipeline/steps/source/_03_setup_source_space.py
mne_bids_pipeline/steps/source/_04_make_forward.py
mne_bids_pipeline/steps/source/_05_make_inverse.py

Closes #748
First run of `ds004229` with the default `epochs_tmax=1`:
```
[13:04:08] ┌╴🚀 preprocessing/_05_make_epochs Now running  👇
[13:04:08] │ ⏳️ preprocessing/_05_make_epochs sub-102 Loading filtered raw data from sub-102_task-amnoise_proc-filt_raw.fif
[13:04:09] │ ⏳️ preprocessing/_05_make_epochs sub-102 Creating task-related epochs …
```
Next run correctly shows as cached:
```
[13:09:25] ┌╴🚀 preprocessing/_05_make_epochs Now running  👇
[13:09:25] │ ✅ preprocessing/_05_make_epochs sub-102 Computation unnecessary (cached) …
[13:09:25] └╴🎉 preprocessing/_05_make_epochs Done running  👆 [1s]
```
Change tmax to 2 it correctly re-runs:
```
[13:17:08] ┌╴🚀 preprocessing/_05_make_epochs Now running  👇
[13:17:08] │ ⏳️ preprocessing/_05_make_epochs sub-102 Loading filtered raw data from …
```

BUG: Fix bug with cache invalidation

---

.circleci/config.yml
.circleci/run_dataset_and_copy_files.sh
.circleci/setup_bash.sh
.github/workflows/circleci-redirector.yml
docs/mkdocs.yml
docs/source/v1.5.md.inc
mne_bids_pipeline/_report.py
mne_bids_pipeline/steps/source/_01_make_bem_surfaces.py
mne_bids_pipeline/steps/source/_04_make_forward.py
mne_bids_pipeline/tests/configs/config_ERP_CORE.py
mne_bids_pipeline/tests/conftest.py
mne_bids_pipeline/tests/test_documented.py
pyproject.toml

1. Refactor BEM report plotting as helper
2. Add it to the BEM surfaces step (will be replaced in the forward step e.g. if the BEM surfaces don't need to be made / already exist, which should be fine)
3. Add back T1_BEM and FLASH_BEM to website now that their reports exist
4. Add some ignores to `mkdocs` using `mkdocs-exclude` plugin to avoid some of the cruft visible here:

ENH: Add T1 and FLASH BEM to website

---

docs/source/v1.5.md.inc
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/steps/preprocessing/_01_data_quality.py
mne_bids_pipeline/steps/preprocessing/_02_head_pos.py
mne_bids_pipeline/steps/preprocessing/_03_maxfilter.py
mne_bids_pipeline/steps/preprocessing/_05_make_epochs.py
mne_bids_pipeline/steps/sensor/_04_time_frequency.py
mne_bids_pipeline/tests/configs/config_ds000246.py

@allermat can you try this branch? In theory you should not need to delete any derivatives, just update to this branch and run.
Closes #759
Only mentioning the `epochs` bug fix here since the one @allermat is actually hitting is a within-release (within the last week I think!) bugfix

BUG: Fix bug with empty room processing

---

docs/source/v1.5.md.inc
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/_config_template.py
mne_bids_pipeline/_logging.py
mne_bids_pipeline/_main.py
mne_bids_pipeline/_report.py
mne_bids_pipeline/_run.py
mne_bids_pipeline/steps/init/_01_init_derivatives_dir.py

@hoechenberger feel free to review/merge if you're happy.
I have been bothered by too much redundancy and overuse of horizontal space in our logging recently. Now that we use `rich` we can make better use of `rule` to avoid redundancy. In particular, currently we print the name of the step at each logging line and it takes up almost a third of the horizontal space (here shown in 132x43 terminal, the largest in the Ubuntu Linux default Terminal drop-down):
With `.rule` we can cleanly log the start of each step as a title and link everything using a consistent color instead (green):
So I think overall this becomes both easier to follow and more compact / less redundant.
Also adds `[link]` support to make the Report HTML Files clickable.

ENH: More compact logging

---

.circleci/config.yml
.circleci/run_dataset_and_copy_files.sh
.circleci/setup_bash.sh
docs/source/v1.5.md.inc
mne_bids_pipeline/__init__.py
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/_logging.py
mne_bids_pipeline/_main.py
mne_bids_pipeline/_parallel.py
mne_bids_pipeline/_report.py
mne_bids_pipeline/_run.py
mne_bids_pipeline/steps/preprocessing/_07a_apply_ica.py
mne_bids_pipeline/steps/sensor/_01_make_evoked.py
mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py
mne_bids_pipeline/steps/sensor/_03_decoding_time_by_time.py
mne_bids_pipeline/steps/sensor/_04_time_frequency.py
mne_bids_pipeline/steps/sensor/_06_make_cov.py
mne_bids_pipeline/steps/sensor/_99_group_average.py
mne_bids_pipeline/steps/source/_05_make_inverse.py
mne_bids_pipeline/steps/source/_99_group_average.py
mne_bids_pipeline/tests/configs/config_ds000248_base.py
mne_bids_pipeline/tests/configs/config_ds001971.py
mne_bids_pipeline/tests/conftest.py
mne_bids_pipeline/tests/test_documented.py
mne_bids_pipeline/tests/test_run.py

I expect some failures because the source grand average step is not complete (these should fail the rerun test!), but this at least runs on `ds003392` and `ds004229` for me locally, and rerunning completes within 10s.
With this PR, I think all cachable steps are cached! Should make rerunning tests faster locally too :rocket:
Closes #609

ENH: Cache grand-average steps

---

docs/source/v1.5.md.inc
mne_bids_pipeline/tests/configs/config_ds001971.py

Looking at coverage I noticed that our MD5 hashing isn't used anywhere. This should increase our coverage a bit and make sure it actually works (including on re-run).

MAINT: Test MD5 hashing too

---

docs/source/v1.5.md.inc
mne_bids_pipeline/steps/source/_04_make_forward.py

On `main` it prints something similar but not via our logging. Now we can control it and get nice logs:
```
┌────────┬ source/_04_make_forward ────────────────────────────────
│14:34:21│ ⏳️ sub-01 Matching template MRI using fiducials
│14:34:22│ ⏳️ sub-01 Median dig ↔ MRI distance:   4.57 mm
│14:34:22│ ⏳️ sub-01 Calculating forward solution
```

ENH: Better logging of distances

---

docs/source/settings/general.md
docs/source/v1.5.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/_run.py

Closes #723
@hoechenberger feel free to mark as merge-when-green if you're happy.

API: Change default to _cache

---

docs/source/v1.5.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/_decoding.py
mne_bids_pipeline/_import_data.py
mne_bids_pipeline/_report.py
mne_bids_pipeline/steps/sensor/_05_decoding_csp.py
mne_bids_pipeline/steps/sensor/_99_group_average.py
mne_bids_pipeline/tests/configs/config_ERP_CORE.py
mne_bids_pipeline/typing.py
pyproject.toml

Locally it seems to work -- adding `config_validation = "foo"` to `config_ds003392.py` for example produces:
```
$ pytest mne_bids_pipeline -xk 003392
...
mne_bids_pipeline/_config_import.py:410: in _pydantic_validate
raise ValueError(str(err)) from None
E   ValueError: 1 validation error for user configuration from /home/larsoner/python/mne-bids-pipeline/mne_bids_pipeline/tests/configs/config_ds003392.py
E   config_validation
E     Input should be 'raise', 'warn' or 'ignore' [type=literal_error, input_value='foo', input_type=str]
E       For further information visit https://errors.pydantic.dev/2.1/v/literal_error
```
or when setting `mf_destination = "foo"` in `config_ds003392.py` which allows a specific Literal or a FloatArrayLike:
```
$ pytest mne_bids_pipeline -xk 004229
... …
```

ENH: Validate inputs with pydantic

---

mne_bids_pipeline/steps/preprocessing/_07a_apply_ica.py
mne_bids_pipeline/steps/preprocessing/_07b_apply_ssp.py
mne_bids_pipeline/steps/preprocessing/_08_ptp_reject.py
mne_bids_pipeline/steps/sensor/_01_make_evoked.py
mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py
mne_bids_pipeline/steps/sensor/_03_decoding_time_by_time.py
mne_bids_pipeline/steps/sensor/_04_time_frequency.py
mne_bids_pipeline/steps/sensor/_05_decoding_csp.py
mne_bids_pipeline/steps/sensor/_06_make_cov.py
mne_bids_pipeline/tests/configs/config_ds000248_base.py

Just a CI re-run to make sure things are actually fixed. Will merge once I double-check the reports and make sure the source plots are fixed. Has the additional benefit of getting the recent report enhancements, too.
Closes #770

TST: Rerun CIs

---

docs/source/v1.5.md.inc
mne_bids_pipeline/_report.py

Reduce logging output when creating and saving reports

---

docs/source/v1.5.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/steps/preprocessing/_07a_apply_ica.py

Do not reject epochs based on PTP threshold before ICA cleaning

---

docs/source/settings/preprocessing/artifacts.md
docs/source/v1.5.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/steps/preprocessing/_08_ptp_reject.py
mne_bids_pipeline/tests/configs/config_ERP_CORE.py
mne_bids_pipeline/tests/conftest.py

Add `"autoreject_local"` as new option for `preprocessing/ptp_reject`

---

docs/source/v1.5.md.inc
mne_bids_pipeline/_parallel.py

Closes #802
Sibling PR of https://github.com/mne-tools/mne-python/pull/12154

BUG: Fix bug with verbosity

---

docs/source/v1.5.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/steps/preprocessing/_06a_run_ica.py
mne_bids_pipeline/steps/preprocessing/_08_ptp_reject.py

This is a fixup for #810
There, not only did we remove bad epochs, but also interpolated data before submission to ICA fitting. However, this is not what is recommended in the autoreject documentation: there, the suggestion is to [only remove the bad epochs](https://autoreject.github.io/stable/auto_examples/plot_autoreject_workflow.html#ica), not interpolate.
This PR fixes the behavior accordingly and updates the documentation and log messages.
I tested on a set of noise EEG data and I'm actually getting better results with this approach for the majority participants .

Do not interpolate bad segments using autoreject before ICA

---

docs/source/v1.5.md.inc
mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py
mne_bids_pipeline/steps/sensor/_03_decoding_time_by_time.py
mne_bids_pipeline/steps/sensor/_05_decoding_csp.py

Addresses https://github.com/mne-tools/mne-python/issues/12197

Omit bad channels when gathering data used for decoding

---

docs/source/v1.5.md.inc

I think this is all we did for 1.4 then cutting a release on GitHub should hopefully do the right thing.
Closes #783

Prepare for 1.5.0 release

---

docs/source/v1.5.md.inc

The "Behavior changes" heading was incorrectly commented out in the changelog

---

.pre-commit-config.yaml
docs/source/v1.6.md.inc
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/_main.py
mne_bids_pipeline/steps/preprocessing/_04_frequency_filter.py
mne_bids_pipeline/steps/sensor/_99_group_average.py
mne_bids_pipeline/tests/configs/config_ds003392.py
mne_bids_pipeline/tests/datasets.py
mne_bids_pipeline/tests/sub-010_ses-t1_scans.tsv
mne_bids_pipeline/tests/test_run.py
pyproject.toml

Some better error messages for path problems, and contains fix for failure in https://github.com/mne-tools/mne-bids-pipeline/pull/833

FIX: Paths and pyarrow

---

docs/source/v1.6.md.inc
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/_main.py
mne_bids_pipeline/_reject.py
mne_bids_pipeline/_run.py
mne_bids_pipeline/steps/freesurfer/_02_coreg_surfaces.py
mne_bids_pipeline/steps/preprocessing/_05_regress_artifact.py
mne_bids_pipeline/steps/preprocessing/_09_ptp_reject.py
mne_bids_pipeline/steps/source/_01_make_bem_surfaces.py
mne_bids_pipeline/steps/source/_02_make_bem_solution.py
mne_bids_pipeline/steps/source/_03_setup_source_space.py

I went to work on #831 but wanted to sort out a few little other bugs (and one minor enhancement) first:
1. Fix bug where using `mf_reference_run = None` could change the empty room file matched from run-to-run of `mne_bids_pipeline` due to use of `set`, whose order is not guaranteed. @hoechenberger I suspect this could be the actual root cause of #814 
2. Output the `reject` params in the reject step -- though this can be set in the config, it's sometimes calculated on-the-fly by `autoreject` and not saved anywhere. Even in the manual `dict` case it's nice to have it near the drop logs in the report in case you want to think about adjusting your thresholds:
4. Fix bug where `reject` was getting restricted incorrectly for M/EEG channels
5. Prefer `stat` to `lstat` because I'm pretty sure …

BUG: Fix several bugs

---

docs/source/v1.6.md.inc
mne_bids_pipeline/_import_data.py
mne_bids_pipeline/steps/preprocessing/_03_maxfilter.py
mne_bids_pipeline/tests/configs/config_ds003392.py

Closes #842
@SophieHerbst feel free to give this branch a shot, it should hopefully fix your issue

BUG: Fix bug with Maxwell step when find_noise_channels_meg=False

---

docs/source/v1.6.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_decoding.py
mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py
mne_bids_pipeline/steps/sensor/_03_decoding_time_by_time.py
mne_bids_pipeline/steps/sensor/_05_decoding_csp.py
mne_bids_pipeline/tests/configs/config_ERP_CORE.py
mne_bids_pipeline/tests/configs/config_ds003392.py
pyproject.toml

When MEG+EEG was used, only EEG was (effectively) being used for classification. This also unifies how rank reduction is done on the data across classifiers as much as possible.
Closes #849

BUG: Fix bug with multichannel classification

---

docs/source/settings/source/inverse.md
docs/source/v1.6.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_main.py
mne_bids_pipeline/_report.py
mne_bids_pipeline/steps/sensor/_06_make_cov.py

Closes #846
Alongside https://github.com/mne-tools/mne-bids/pull/1227 and https://github.com/mne-tools/mne-python/pull/12447 produces for example:
| [main](https://mne.tools/mne-bids-pipeline/dev/examples/MNE-phantom-KIT-data/sub-average_task-phantom_report.html#Event_counts) | PR |
| -- | -- |
| ![Screenshot from 2024-02-16 16-20-29](https://github.com/mne-tools/mne-bids-pipeline/assets/2365790/c528ca6b-6448-47f0-ad46-5836a06dc7da) | ![Screenshot from 2024-02-16 16-30-59](https://github.com/mne-tools/mne-bids-pipeline/assets/2365790/993fcdc8-39ce-4f23-8080-bd428db74a8f) |
It's more impressive on other examples but you can at least see that it turns it into a datatable and also fixes the overflow.
Also:
- Snuck in a `noise_cov_method = "shrunk"` option, too. It's useful when debugging to …

ENH: Better event count rep and noise_cov_method

---

.circleci/config.yml
.circleci/setup_bash.sh
CONTRIBUTING.md
Makefile
docs/source/examples/gen_examples.py
docs/source/v1.6.md.inc
mne_bids_pipeline/_download.py
mne_bids_pipeline/tests/datasets.py
pyproject.toml

Lately it seems like a larger number of our CircleCI builds are [failing](https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/4275/workflows/e2dc0447-b732-4a79-bab9-e54cdcbc4d35/jobs/58831) due to `git-annex-standalone` installation failing. We don't use it anymore (because it didn't work well!) and it doesn't sound super well maintained, so let's get rid of it. Removed some `"osf"` cruft, too. (FWIW `git` history makes it pretty easy to get this stuff back later if we really want it, but I'd assume YAGNI.)

MAINT: Remove datalad

---

docs/hooks.py
docs/mkdocs.yml
docs/source/settings/gen_settings.py
docs/source/v1.6.md.inc
docs/templates/python/material/_base/attribute.html
mne_bids_pipeline/steps/freesurfer/_02_coreg_surfaces.py
mne_bids_pipeline/steps/preprocessing/_01_data_quality.py
mne_bids_pipeline/steps/sensor/_99_group_average.py
mne_bids_pipeline/steps/source/_04_make_forward.py

Closes #862
Examples:
(I didn't realize `use_maxwell_filter` had a direct impact on the CSP step but it does because we pick `mag` there if it's used!)
Draft because I need to parse a few functions for `config` defs but that's a tiny detail -- the general idea and code is otherwise reviewable.

ENH: Document relevant steps

---

docs/source/v1.6.md.inc
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/_run.py

Closes #868
Result:
@hoechenberger in principle we *could* split this into multiple rows, but I think it's perhaps nicer this way -- if you want to see a multiline value you click in the cell and you can see it, select, copy-paste etc. If we put in multiple rows it might not be as easy to do that.
The truncation code is still present, but it really only applies to the `DigMontage` because its `json_tricks` dump is so long (contains all channel locations, coord frame, etc from `DigMontage`.).
Also this contains *all* config values, both those supplied by the user and those that are defaults. I think it's nice because it shows all values that are used. If people want to know which values they supplied, that complementary information is in the `_report.html` files.

ENH: Doc config in sheet

---

docs/source/v1.7.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/steps/sensor/_01_make_evoked.py
mne_bids_pipeline/steps/sensor/_06_make_cov.py
mne_bids_pipeline/tests/configs/config_ERP_CORE.py

This was reported at https://mne.discourse.group/t/error-when-setting-analyze-channels-using-mne-bids-pipeline

Fix handling of `analyze_channels` for EEG data, where some steps (like ERP calculation) would previously fail

---

docs/hooks.py
docs/source/changes.md
docs/source/v1.8.md.inc
mne_bids_pipeline/_config.py

Remove ancient config parameter `shortest_event`

---

docs/source/examples/gen_examples.py
docs/source/v1.8.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/_decoding.py
mne_bids_pipeline/_import_data.py
mne_bids_pipeline/_io.py
mne_bids_pipeline/_report.py
mne_bids_pipeline/_run.py
mne_bids_pipeline/steps/init/_02_find_empty_room.py
mne_bids_pipeline/steps/preprocessing/_01_data_quality.py
mne_bids_pipeline/steps/sensor/_05_decoding_csp.py
mne_bids_pipeline/steps/sensor/_06_make_cov.py
mne_bids_pipeline/steps/sensor/_99_group_average.py
mne_bids_pipeline/steps/source/_02_make_bem_solution.py
mne_bids_pipeline/tests/configs/config_ds000117.py
mne_bids_pipeline/tests/configs/config_ds003392.py
mne_bids_pipeline/tests/conftest.py

Closes #882
Closes #876
Also updated the doc of `decoding_csp_times = None` as this is *not* a no-op.

BUG: Fix bug with CSP computation and Maxwell filter

---

mne_bids_pipeline/_report.py

Don't think this one needs a changelog update, but I was getting an error related to NumPy import and just printing the `exc` itself wasn't enough to see it.

MAINT: Print longer traceback on report error

---

.github/dependabot.yml
docs/source/changes.md
docs/source/v1.8.md.inc
docs/source/v1.9.md.inc

@larsoner I realized I **again** forgot to include the release data in the changelog. This consistently happens to me … So I now simply removed that part from the 1.9 changelog. Feel free to revert :D

Set up Dependabot to automatically keep GitHub Actions up-to-date

---

docs/mkdocs.yml

Render type annotations in the documentation again

---

docs/mkdocs.yml
docs/source/settings/gen_settings.py
docs/source/v1.9.md.inc
mne_bids_pipeline/_config.py

I've replaced the `Execution` section with the folliwing new sections
- Caching
- Parallelization
- Logging
- Error handling

Restructure configuration options documentation sections

---

docs/source/v1.9.md.inc
mne_bids_pipeline/_config.py

enhance documentation of caching, continuation of #914

---

.circleci/config.yml
docs/source/v1.9.md.inc
mne_bids_pipeline/_config.py

@larsoner @SophieHerbst WDYT?
We currently don't support volumetric or mixed source spaces anyway, so I thought we could simplify things a little.
I was even considering entirely removing the `loose` and `depth` settings but then wasn't sure if some of you might be using them sometimes? Personally I never touch those.

Improve documentation and config validation of `loose` and `depth` parameters; drop support for `loose=None`

---

.pre-commit-config.yaml
docs/source/v1.9.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/steps/source/_04_make_forward.py
mne_bids_pipeline/steps/source/_05_make_inverse.py

Change default for info given to 05_make_inverse.py (and for consistency 04_make_forward.py):
If set to `None` (default), the info will be retrieved either from the raw
file specified in `noise_cov`, or the cleaned epochs (if `noise_cov` is None or `ad-hoc`).
Closes #905

change default for info to use for inverse #905

---

.circleci/config.yml
.circleci/remove_examples.sh
.circleci/setup_bash.sh
docs/source/examples/gen_examples.py
docs/source/v1.9.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_run.py
mne_bids_pipeline/steps/preprocessing/_06a1_fit_ica.py
mne_bids_pipeline/steps/preprocessing/_06a2_find_ica_artifacts.py
mne_bids_pipeline/steps/preprocessing/_08a_apply_ica.py
mne_bids_pipeline/tests/configs/config_ERP_CORE.py
mne_bids_pipeline/tests/conftest.py

1. Moved all ICA reports to the main report:
2. Added docs suggesting manual intervention is required (maybe it should be suggested instead?) when using ICA to take care of the doc part of #881
3. Add just one subject's data for `ERP_CORE` (plus the average) to the website to cut size down.
4. Add script to remove examples from old versions so we don't have to remove their docs anymore (they go down to like 6MB or something!).
Closes #880

ENH: Streamline ICA reporting

---

docs/source/v1.9.md.inc
mne_bids_pipeline/_config_utils.py

This PR:
```python
FileNotFoundError: The following requested subjects were not found in the dataset: 774
```
`main`:
```python
FileNotFoundError: Root directory does not exist: "/Users/richardhochenberger/Library/CloudStorage/OneDrive-dsm-firmenich/Documents/TasIn/data/raw_bids/sub-774"
```

Raise a more helpful error message when requested subjects are missing from the dataset

---

docs/source/v1.9.md.inc
mne_bids_pipeline/_report.py

In the report TOC, don't put the run numbers in quotation marks

---

docs/source/v1.9.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/steps/preprocessing/_06a2_find_ica_artifacts.py

- Consistency with `ica_eog_threshold`
- Allows us to later add support for additional ECG-detection methods

Rename `ica_ctps_ecg_threshold` to `ica_ecg_threshold`

---

docs/source/v1.9.md.inc
mne_bids_pipeline/steps/preprocessing/_06a1_fit_ica.py
mne_bids_pipeline/steps/preprocessing/_08a_apply_ica.py
mne_bids_pipeline/steps/preprocessing/_08b_apply_ssp.py
mne_bids_pipeline/steps/preprocessing/_09_ptp_reject.py

quite some duplication … but Logging is better
```
┌────────┬ preprocessing/_09_ptp_reject ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│21:45:35│ ⏳️ sub-005 Input:  sub-005_task-tasin_proc-ica_epo.fif
│21:45:35│ ⏳️ sub-005 Output: sub-005_task-tasin_proc-clean_epo.fif
│21:45:36│ ⏳️ sub-005 Removed 4 of 240 epochs via PTP rejection thresholds: {'eeg': 0.00025}
│21:45:36│ ⏳️ sub-005 Adding cleaned epochs to report.
```

Improve logging output when rejecting epochs; and log number of reconstructed ICA and SSP epochs

---

.circleci/config.yml
docs/source/v1.9.md.inc

Of course some typo snuck through while the CIs couldn't fully build! Will mark for auto merge then hopefully we'll be back to green on `main`

DOC: Fix typo

---

docs/hooks.py

No need for changelog update I think since this is really just internal cleanup. Trying the suggestion in https://github.com/mkdocstrings/mkdocstrings/issues/615#issuecomment-2081550319

MAINT: Cleaner hook into mkdocstrings-python

---

.github/workflows/release.yml

Discussed with @larsoner: https://github.com/mne-tools/mne-connectivity/pull/200#issuecomment-2163383202
Switches releases to support PyPI trusted publishing.

[MAINT] Switch to trusted publishing

---

docs/source/v1.9.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_import_data.py

- When applying montages, check for channel aliases, too (e.g. `M1 -> TP9`).
- Raise an exception (not just a warning) if the data contains channels that are not part of the montage.
Reported in #958

Rework how we apply EEG montages

---

docs/mkdocs.yml
docs/source/v1.10.md.inc

Choose documentation color scheme automatically based on operating system setting

---

docs/build-docs.sh
docs/mkdocs.yml
docs/source/getting_started/freesurfer.md
mne_bids_pipeline/tests/conftest.py

Be stricter when building documentation

---

docs/mkdocs.yml
docs/source/v1.10.md.inc

Vendor external JavaScript with our documentation to better preserve users' privacy

---

docs/source/v1.10.md.inc
mne_bids_pipeline/steps/preprocessing/_03_maxfilter.py

clarify maxfilter log message

---

.github/workflows/run-tests.yml
docs/source/v1.10.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/_docs.py
mne_bids_pipeline/steps/init/_01_init_derivatives_dir.py
mne_bids_pipeline/steps/init/_02_find_empty_room.py
mne_bids_pipeline/steps/preprocessing/_01_data_quality.py
mne_bids_pipeline/steps/preprocessing/_02_head_pos.py
mne_bids_pipeline/steps/preprocessing/_03_maxfilter.py
mne_bids_pipeline/steps/preprocessing/_04_frequency_filter.py
mne_bids_pipeline/steps/preprocessing/_05_regress_artifact.py
mne_bids_pipeline/steps/preprocessing/_06a1_fit_ica.py
mne_bids_pipeline/steps/preprocessing/_06a2_find_ica_artifacts.py
mne_bids_pipeline/steps/preprocessing/_06b_run_ssp.py
mne_bids_pipeline/steps/preprocessing/_07_make_epochs.py
mne_bids_pipeline/steps/preprocessing/_08a_apply_ica.py
mne_bids_pipeline/steps/preprocessing/_08b_apply_ssp.py
mne_bids_pipeline/steps/preprocessing/_09_ptp_reject.py
mne_bids_pipeline/steps/sensor/_01_make_evoked.py
mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py
mne_bids_pipeline/steps/sensor/_03_decoding_time_by_time.py
mne_bids_pipeline/steps/sensor/_04_time_frequency.py
mne_bids_pipeline/steps/sensor/_05_decoding_csp.py
mne_bids_pipeline/steps/sensor/_06_make_cov.py
mne_bids_pipeline/steps/source/_04_make_forward.py
mne_bids_pipeline/steps/source/_05_make_inverse.py
mne_bids_pipeline/steps/source/_99_group_average.py
mne_bids_pipeline/tests/test_run.py

allow missing sessions

---

docs/source/v1.10.md.inc
mne_bids_pipeline/steps/source/_04_make_forward.py

BUG: Fix bug with forward creation

---

.github/workflows/run-tests.yml

`continue-on-error: true` can lead to "successful" builds that had a failing step when `if: always()` is used, so just avoid it. Achieve the desired effect of not killing other *jobs* early with `fail-fast: false` instead.

MAINT: Dont use continue-on-error

---

docs/source/dev.md.inc
mne_bids_pipeline/_import_data.py

remove EEG channels from emptyroom when preparing it for maxwell filter

---

.circleci/config.yml
.github/workflows/run-tests.yml
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/tests/test_run.py
pyproject.toml

The addition of `allow_missing_sessions` in #1000 had some problems:
1. it was storing `[None]` in the `subjs_sessions` dict in cases where a subject had no valid sessions; this was not behaving as expected
2. the use of `mne_bids.get_entity_vals` was not working as expected, because even if a subject had no *data* for a session for a given task, the presence of `coordsystem.json` or `scans.tsv` sidecars was causing it to report that the subject had *some files* for that session.
Item (2) was fixed in https://github.com/mne-tools/mne-bids/pull/1362; item (1) is fixed here. Works on my data, but will self-review to add some questions about implementation/testing.

fix ignoring sessions that have no data

---

.github/workflows/run-tests.yml
docs/mkdocs.yml
docs/source/dev.md.inc
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/steps/freesurfer/_01_recon_all.py
mne_bids_pipeline/steps/source/_01_make_bem_surfaces.py
mne_bids_pipeline/tests/datasets.py
mne_bids_pipeline/tests/test_run.py

~~Per conversation with @larsoner I'm splitting out the work of adding the funloc dataset (and fixing the bugs it reveals) to make the diff cleaner on #1035 (which is actually dealing with a different problem than what funloc addresses --- #1035 is about skipping missing sessions, not handling session-specific anat).~~
This PR has been rebased after #1045 was merged, so now all it does is monkeypatch the funloc dataset to test support for session-specific MRIs.

Improve (and test) support for session-specific MRIs

---

mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_import.py
mne_bids_pipeline/steps/preprocessing/_02_head_pos.py
mne_bids_pipeline/steps/preprocessing/_03_maxfilter.py
mne_bids_pipeline/tests/configs/config_ds004229.py
mne_bids_pipeline/tests/test_validation.py

Opening this for early feedback. So far it looks like it won't require a very big diff, but perhaps that's the naïvety of not having tested it yet 🙈. Could probably be tested with `funloc` once that's finished / merged.

add framework for TWA head pos as MF destination

---

mne_bids_pipeline/_config.py

Fixes the example admonition on https://mne.tools/mne-bids-pipeline/stable/settings/preprocessing/maxfilter.html#mne_bids_pipeline._config.mf_destination

fix config example in docs

---

docs/source/dev.md.inc
mne_bids_pipeline/steps/preprocessing/_02_head_pos.py
mne_bids_pipeline/steps/preprocessing/_03_maxfilter.py

fixup for TWA-HP (gh1043)

---

docs/source/dev.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/steps/preprocessing/_01_data_quality.py
mne_bids_pipeline/steps/preprocessing/_03_maxfilter.py
mne_bids_pipeline/tests/configs/config_ds000248_mf.py
mne_bids_pipeline/tests/test_run.py

Trying to push Cerca OPM data through the pipeline.
We don't have calibration or ctc files for our OPM system. IIUC Seems like both are necessary, because we 1) estimate sensor orientations during coreg (so raw.info should be 'correct') and 2) we only use magnetometers. 
The MNE maxwell functions allow for `calibration` and `cross_talk` to be passed as None, so should be allowed here as well.

allow calibration and ctc files to be None

---

docs/source/dev.md.inc
mne_bids_pipeline/_config_utils.py
mne_bids_pipeline/steps/sensor/_99_group_average.py
mne_bids_pipeline/steps/source/_01_make_bem_surfaces.py
mne_bids_pipeline/steps/source/_02_make_bem_solution.py
mne_bids_pipeline/steps/source/_03_setup_source_space.py
mne_bids_pipeline/steps/source/_99_group_average.py
mne_bids_pipeline/tests/test_validation.py

a couple of late pipeline steps are still not robust to the `allow_missing_sessions` kwarg. ~~So far~~ this PR fixes:
~~probably I'll hit more as I churn through this dataset, so marking as draft for now; I'm facing the dreaded BEM error "The source surface has a matching number of triangles but ordering is wrong" so I need to get that unblocked before I can find out if later steps are also failing due to missing sessions.~~

make late pipeline steps robust to missing sessions

---

docs/source/dev.md.inc
mne_bids_pipeline/_import_data.py
mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py
mne_bids_pipeline/steps/sensor/_03_decoding_time_by_time.py
mne_bids_pipeline/steps/sensor/_05_decoding_csp.py

First smal PR :)
This drops the use of legacy `Raw.pick_types` and `Epochs.pick_types` in favor of `.pick(...)`.
See #973

Drop `Raw.pick_types` and `Epochs.pick_types`

---

docs/source/dev.md.inc
mne_bids_pipeline/_config.py
mne_bids_pipeline/_config_template.py
mne_bids_pipeline/tests/test_documented.py

on `main`, template config files have a couple of bad features:
these lines get commented out, making the file syntactically invalid (unclosed parens):
https://github.com/mne-tools/mne-bids-pipeline/blob/6005b52381203ed3993dc1cc4943e8fd507f993b/mne_bids_pipeline/_config.py#L11-L15
this line does not get commented out, because it starts with "from":
https://github.com/mne-tools/mne-bids-pipeline/blob/6005b52381203ed3993dc1cc4943e8fd507f993b/mne_bids_pipeline/_config.py#L348
This PR:

fixup generation of template config files

---

docs/source/dev.md.inc
mne_bids_pipeline/_report.py
mne_bids_pipeline/tests/configs/config_ds001810.py

Currently, contrasts from metadata (e.g., `cond == "A"`) won't create valid report tags due to illegal characters (`"`, `'`).
PR properly sanitizes these tags. Added metadata-based decoding to test suite in `ds001810`.
edit: Wondered if this should be fixed at `mne-python` level, but really only an issue if you auto-generate tags.

FIX: sanitize tags
