01-frequency_filtering.py, 02-maxwell_filtering.py, 04-artifact_correction_ica.py, 05-make_epochs.py, config.py
moving towards a MWE of the pipeline, using `sample`
=> review current scripts

01-import_and_filter.py, 02-apply_maxwell_filter.py, README.md, config.py
allow for definition of bad channels per run
if plot = True, plot single runs
=> Bads per run

01-import_and_filter.py, 02-apply_maxwell_filter.py, 03-extract_events.py, 04-make_epochs.py, 05a-run_ica.py, 07-make_evoked.py, 08-group_average_sensors.py, 09-sliding_estimator.py, 10-time_frequency.py, 11-make_forward.py, 12-make_cov.py, 13-make_inverse.py, 14-group_average_source.py, config.py
define only the base name in config, add extensions in every file
=> Make file naming more consistent over scripts

05a-run_ica.py, 05b-compute_and_apply_ssp.py, 06a-apply_ica.py, 09-sliding_estimator.py, Makefile, config.py
Zut. Again forgot to properly update my master. 
new stuff starts with e54d48d.
=> Apply ica new

.circleci/config.yml, tests/configs/config_ds000117.py, tests/configs/config_ds001810.py, tests/configs/config_ds001971.py, tests/download_test_data.py
=> use mne config to determine data dir

.circleci/config.yml, CONTRIBUTING.md, config.py, tests/configs/config_ds000117.py
=> [MRG] remove pybids dependency

.circleci/config.yml, tests/configs/config_matchingpennies.py, tests/download_test_data.py
=> [MRG] add EEG_matchingpennies to testing data

.circleci/config.yml, 01-import_and_filter.py, config.py, tests/configs/config_ds000246.py, tests/download_test_data.py
=> MRG, ENH: add ds000246 to testing

config.py
=> update get_values_from_key -> get_entity_vals

README.md
found two broken links due to outdated script names in Readme's table
=> fix links in Readme

09-sliding_estimator.py
very small typo, legression for regression on the first sentence
=> typo correction

99-make_reports.py
Don't use an arbitrary time index as before.
=> MRG: ENH: Plot STC at time of peak amplitude

config.py
The reason why this was never caught by our CI is that all test config files do contain this key.
=> MRG: BF: Steps 8, 9, 13, 14, 99 require study_name

.circleci/config.yml, 13-make_inverse.py, 14-group_average_source.py, 99-make_reports.py
Closes GH-81.
STC naming for a sample participant:
```
sub-CC110033_inverse-dSPM-audiovis1200Hz-fsaverage-lh.stc
sub-CC110033_inverse-dSPM-audiovis1200Hz-fsaverage-rh.stc
sub-CC110033_inverse-dSPM-audiovis1200Hz-lh.stc
sub-CC110033_inverse-dSPM-audiovis1200Hz-rh.stc
```
WDYT?
=> MRG: Same namig scheme for regular & fsaverage STC

12-make_inverse.py
We already use this during noise cov calculation, so we should use the very same setting here.
=> BF: Set rank='info' during make_inverse_operator()

.circleci/config.yml, 01-import_and_maxfilter.py, 02-frequency_filter.py, 03-make_epochs.py, 04a-run_ica.py, 04b-run_ssp.py, 05a-apply_ica.py, 05b-apply_ssp.py, 06-make_evoked.py, 07-group_average_sensors.py, 08-sliding_estimator.py, 09-time_frequency.py, 10-make_forward.py, 11-make_cov.py, 12-make_inverse.py, 13-group_average_source.py, 99-make_reports.py, config.py
Closes GH-70.
- introduces `config.log_level` to control pipeline logging, and `config.mne_log_level` to control MNE logging
- adds `config.gen_log_message()` to generate a message string consisting of the message itself, the pipeline step, participant ID, session name, and run number
- makes use of the [`coloredlogs`](https://coloredlogs.readthedocs.io/en/latest/) package, which provides a great and cross-platform way to make the logs more readable by adding color or changing the font weight
=> WIP: ENH: Add logging mechanism

99-make_reports.py, config.py
Do not render alignment when no valid MNE 3d backend has been set. **STCs will berendered** via Matplotlib in this case.
Depends on https://github.com/mne-tools/mne-python/pull/7708 and will therefore currently only work with `mne-python:master`
=> BF: Still render if we don't have a 3d backend

.circleci/config.yml, 04a-run_ica.py, config.py
=> ENH: Allow for ICA algorithm selection

config.py
Display the config filename now.
=> Better log message when using custom config

01-import_and_maxfilter.py
To declutter the HUGE `run_maxwell_filter()` function these steps are part of.
=> Factor out event renaming and bads detection

01-import_and_maxfilter.py
The reason I'm doing all of this refactoring is to make the code easier to understand and maintain, and also I hope I can reuse more "measurement processing" code when doing the "emptyroom processing".
=> RF: Factor out Maxwell filter step into own function

01-import_and_maxfilter.py, 02-frequency_filter.py, 03-make_epochs.py, 04a-run_ica.py, 04b-run_ssp.py, 05a-apply_ica.py, 05b-apply_ssp.py, 06-make_evoked.py, 07-group_average_sensors.py, 08-sliding_estimator.py, 09-time_frequency.py, 10-make_forward.py, 11-make_cov.py, 12-make_inverse.py, 13-group_average_source.py, 99-make_reports.py, config.py
The common task of creating the path to the directory where the data is stored for a particular participant & recording kind has now been moved into the `config.get_subject_path()` function.
=> Add config.get_subject_path(), config.get_subject_deriv_path()

01-import_and_maxfilter.py, 02-frequency_filter.py, 10-make_forward.py, 11-make_cov.py, 99-make_reports.py, config.py, tests/configs/config_ds000248.py, tests/download_test_data.py, tests/run_tests.py
=> [MRG] NF: Add emptyroom handling

99-make_reports.py
Otherwise the required files may not be found in some cases.
=> Pass subjects_dir to plot_alignment() & stc.plot()

config.py
This should be handled at the BIDS level.
Closes #136.
=> Remove trigger_time_shift

99-make_reports.py
Fix a bug introduced in GH-147 that prevented STC rendering in the reports (except for grand average reports).
=> [MRG] BF: Include STC plots in reports

01-import_and_maxfilter.py, 99-make_reports.py
=> Use logger.warning instead of .warn

01-import_and_maxfilter.py, 03-make_epochs.py, 04a-run_ica.py, 05a-apply_ica.py, config.py
So we don't have to worry about it during later processing steps!
=> WIP: Pick the requested channel type early

01-import_and_maxfilter.py, 08-sliding_estimator.py, 09-time_frequency.py, 99-make_reports.py, config.py
- Replace use of os.path.join with BIDSPath where possible
- More consistency of file names
- Better filename sanitization in some places
- And some other minor cleanups
=> Misc. cleanups

01-import_and_maxfilter.py, config.py
Channel names and types should all be handled via BIDS!
=> [MRG] Remove channel renaming & channel type settings; support latest MNE-BIDS

01-import_and_maxfilter.py, 02-frequency_filter.py, 03-make_epochs.py, 04a-run_ica.py, 04b-run_ssp.py, 05a-apply_ica.py, 05b-apply_ssp.py, 06-make_evoked.py, 07-group_average_sensors.py, 08-sliding_estimator.py, 09-time_frequency.py, 10-make_forward.py, 11-make_cov.py, 12-make_inverse.py, 13-group_average_source.py, 99-make_reports.py
Don't include transition of ICA code; will be handled in GH-163
=> Support latest MNE-BIDS changes (BIDSPath)

01-import_and_maxfilter.py, 02-frequency_filter.py, 03-make_epochs.py, 04b-run_ssp.py, 05b-apply_ssp.py, 06-make_evoked.py, 09-time_frequency.py, 10-make_forward.py, 11-make_cov.py, 12-make_inverse.py, 13-group_average_source.py, 99-make_reports.py
Following https://github.com/mne-tools/mne-bids/pull/523
=> [MRG] Use bids_path instead of bids_basename

99-make_reports.py
https://github.com/mne-tools/mne-python/pull/8169
=> No need for workaround anymore, thanks to upstream fix

config.py, tests/configs/config_ds000117.py, tests/configs/config_ds000246.py, tests/configs/config_ds000248.py, tests/configs/config_ds000248_ica.py, tests/configs/config_ds001810.py, tests/configs/config_ds001971.py, tests/configs/config_eeg_matchingpennies.py
More consistent with the rest of our naming scheme!
=> MRG: subjects_list -> subjects

01-import_and_maxfilter.py, config.py
=> add option to fix stimulation artifact

config.py, docs/mkdocs.yml, docs/source/css/extra.css, docs/source/index.md, docs/source/install.md
- Better a11y by increasing font sizes in some places
- In config options overview, make settings names bold
- Add some abbreviations
=> [MRG] Some doc tweaks

config.py, run_freesurfer.py
@hoechenberger still WIP but let me know what you think
=> MRG: add run_freesurfer.py

.circleci/config.yml, config.py, docs/source/settings/preprocessing/maxfilter.md, scripts/preprocessing/01-import_and_maxfilter.py, tests/configs/config_ds000117.py, tests/configs/config_ds000248.py, tests/download_test_data.py, tests/requirements.txt
We can now find these files thanks to the BIDS specification.
Re-enable ds000248 tests, thanks to @agramfort who managed to update the
dataset.
=> Remove MEG fine-cal & crosstalk config options

.circleci/config.yml, run.py, scripts/preprocessing/04a-run_ica.py, tests/configs/config_ds003392.py, tests/download_test_data.py, tests/requirements.txt, tests/run_tests.py
=> Process localizer data & fix bug in ICA (didn't operate on existing filtered data)

.circleci/config.yml, config.py, docs/mkdocs.yml, tests/configs/config_ds000117.py, tests/run_tests.py
Remaining / highlighted issues:
- Original dataset doesn't store fine-calibration and crosstalk files according to BIDS, so not doing Maxwell filtering for now
- I'd like to calculate the contrast of "face" vs "scrambled", however, to do that, I'd need to merge the "familiar" and "unfamiliar" events to "faces". We need to add support for operations like this.
Tests will fail until https://github.com/mne-tools/mne-bids/pull/680 has been merged.
=> Process Faces dataset

config.py, scripts/preprocessing/03-make_epochs.py
see https://mne.tools/mne-biomag-group-demo/auto_scripts/library/config.html#sphx-glr-auto-scripts-library-config-py
where it was used @hoechenberger
=> missing reject_tmax from config

config.py, docs/source/settings/general.md, scripts/preprocessing/04a-run_ica.py, scripts/preprocessing/04b-run_ssp.py
=> Allow speficition of custom EOG channel(s)

config.py, scripts/preprocessing/01-import_and_maxfilter.py
- Address type variable naming comments by @agramfort
- Specify eeg_bipolar_channels as a dict (not tuple)
=> Misc small changes

config.py, docs/source/settings/general.md, tests/configs/config_ds000246.py
`deriv_root` can now be set to control the output directory.
cc @guiomar
=> Add new config option to set derivatives root

config.py, docs/source/settings/general.md, scripts/preprocessing/01-import_and_maxfilter.py, scripts/report/01-make_reports.py, tests/configs/config_ds000246.py
Closes #159, #160
Thanks @guiomar for updating the ds000246 dataset!!
=> Remove anonymiztion option

config.py, docs/source/settings/preprocessing/epochs.md, scripts/preprocessing/03-make_epochs.py, scripts/preprocessing/04a-run_ica.py
Preparation for the introduction of metadata_[tmin,tmax]
=> Rename tmin, tmax to epochs_[tmin,tmax] + some minor doc tweaks

scripts/preprocessing/01-import_and_maxfilter.py
This should fix your problem, @amellot
cc @agramfort
=> BUG: We tried to read fine-calibration as cross-talk file

config.py, docs/mkdocs.yml, docs/source/settings/preprocessing/epochs.md, docs/source/settings/source/general.md, erp_core.py, scripts/preprocessing/01-import_and_maxfilter.py, scripts/preprocessing/02-frequency_filter.py, scripts/preprocessing/03-make_epochs.py, scripts/preprocessing/04a-run_ica.py, scripts/preprocessing/05a-apply_ica.py, scripts/preprocessing/05b-apply_ssp.py, scripts/report/01-make_reports.py, scripts/sensor/01-make_evoked.py, scripts/sensor/02-sliding_estimator.py, scripts/sensor/04-group_average.py, scripts/source/01-make_bem_surfaces.py, scripts/source/02-make_forward.py, scripts/source/03-make_cov.py, scripts/source/04-make_inverse.py, scripts/source/05-group_average.py
This PR adds support for metadata creation, applies baseline correction only after ICA (not before), and slightly improves ICA reports and some log messages.
=> Various changes for metadata & ERP CORE processing

.circleci/config.yml, .github/workflows/circleci-redirector.yml, docs/source/examples/gen_examples.py, tests/environment.yml
Let's see if testing ds003392 works. If it does, I can make the rest of the datasets work the same way. So I'm expecting / hoping `test_ds003392` to work first (and `build_docs` will fail), then I'll try to get `build_docs` working, then probably the rest of the tests.
=> MAINT: Refactor CircleCI

.circleci/config.yml
=> Manually create PyVista settings dir

scripts/preprocessing/01-import_and_maxfilter.py, scripts/preprocessing/04a-run_ica.py, scripts/preprocessing/04b-run_ssp.py, tests/configs/config_ERP_CORE.py
Also make ERP CORE config more explicit regarding
EOG specification
=> Ensure bipolar EOG channels have correct type

run.py, scripts/preprocessing/04a-run_ica.py, scripts/preprocessing/04b-run_ssp.py
pb found while playing with the data from @ktavabi
=> FIX : deal with no ECG or EOG events found

docs/source/settings/preprocessing/epochs.md
=> Add metadata_keep_first, keep_last to rendered doc

config.py, scripts/preprocessing/04a-run_ica.py
Fixes #285
- More validation
- drop support for "dangerous" stuff (no filtering, cutoff < 1 Hz)
We need to decide sometime where and when to do the validation: in the config file or in the scripts?
cc @MerlinDumeur @agramfort
=> Rework high-pass filtering for ICA

docs/source/changes.md, scripts/preprocessing/04a-run_ica.py, tests/configs/config_ds000248_ica.py
=> Fix extended_infomax ICA method

docs/source/changes.md, scripts/preprocessing/01-import_and_maxfilter.py
=> Fix handling of eog_channels=None

docs/source/changes.md, scripts/source/02-make_forward.py
=> Adding information on FileNotFoundError when making bem model

config.py, docs/source/changes.md, docs/source/examples/gen_examples.py, docs/source/settings/preprocessing/ssp_ica.md, scripts/preprocessing/04a-run_ica.py, scripts/preprocessing/04b-run_ssp.py, scripts/preprocessing/05a-apply_ica.py, scripts/preprocessing/05b-apply_ssp.py, scripts/preprocessing/06-ptp_reject.py, scripts/report/01-make_reports.py, scripts/sensor/01-make_evoked.py, scripts/sensor/03-time_frequency.py, scripts/source/03-make_cov.py, tests/configs/config_ERP_CORE.py, tests/configs/config_ds000117.py, tests/configs/config_ds000248_ica.py, tests/configs/config_ds001810.py, tests/configs/config_ds001971.py, tests/configs/config_ds003392.py, tests/configs/config_eeg_matchingpennies.py
@guiomar @agramfort WDYT?
x-ref: #314
=> No SSP by default; remove "use_{ica,ssp}" settings in favor of new setting "spatial_filter"

config.py, docs/source/changes.md, scripts/preprocessing/01-import_and_maxfilter.py, scripts/report/01-make_reports.py, scripts/source/03-make_cov.py, tests/configs/config_ds003392.py
It's superfluous now that https://github.com/mne-tools/mne-bids/pull/788 has been merged.
=> Drop allow_maxshield config option

docs/source/changes.md, scripts/preprocessing/01-import_and_maxfilter.py, scripts/preprocessing/03-make_epochs.py, scripts/preprocessing/05a-apply_ica.py, scripts/preprocessing/05b-apply_ssp.py, scripts/preprocessing/06-ptp_reject.py, scripts/sensor/01-make_evoked.py
=> use head origin to find bads

docs/source/changes.md, scripts/preprocessing/05a-apply_ica.py, scripts/preprocessing/06-ptp_reject.py, scripts/report/01-make_reports.py
=> Baseline correct data for ICA overlay plots

CONTRIBUTING.md, LICENSE.txt
=> add license and CoC link

docs/source/changes.md, docs/source/governance.md, tests/requirements.txt
=> MAINT: Add gov doc

docs/source/getting_started/install.md, tests/environment.yml, tests/requirements.txt
I've updated our ERP CORE data on OSF with bad channel descriptions provided by the original authors
This PR is just to enforce a re-run of our CI with the updated data.
=> Test amended ERP CORE

scripts/preprocessing/03-make_epochs.py
=> no proj ON in unclean epochs

.circleci/config.yml
cc @larsoner
let's see if this works
=> Switch to different keyserver

docs/source/changes.md, scripts/preprocessing/04a-run_ica.py
=> add warning when 0 EOG/ECG-related IC detected ?

.circleci/config.yml, config.py, docs/build-docs.sh, docs/source/changes.md
=> configuration: `conditions` parameter set to None

config.py, docs/source/changes.md, docs/source/settings/general.md, scripts/preprocessing/01-import_and_maxfilter.py, tests/configs/config_ds000117.py
=> Rename config.crop to config.crop_runs

.circleci/config.yml
=> Simplify Circle config

config.py, docs/source/changes.md
Closes #356.
I used `isinstance(baseline[0], numbers.Number)`, which is a practical way of handling the cases with t=0 or t=None.
=> Baseline interval check

config.py, docs/source/changes.md, docs/source/getting_started/install.md, scripts/report/01-make_reports.py, scripts/sensor/03-time_frequency.py, tests/configs/config_ds000248.py, tests/requirements.txt
I noticed that AverageTFR was calculated but not displayed in the reports. So this adds a display for the computed TFR. It also allows the user to set the frequency limits.
However, I am not sure what is the best representation of the data to show. So to open the discussion I have added the topo figure. Is there a better way to display this data in the reports?
Also if this won't be useful to others then please close. This is mainly just me learning the repo.
=> Add TFR to reports

config.py, docs/source/changes.md, docs/source/settings/general.md
=> add exclude_runs

scripts/preprocessing/04a-run_ica.py
=> reject in ICA early and not just in fit to clean plot_properties

.circleci/config.yml
=> Try to fix doc deployment

config.py, docs/source/changes.md, scripts/init/00-init_derivatives_dir.py, scripts/preprocessing/01-maxfilter.py, scripts/preprocessing/02-frequency_filter.py, scripts/preprocessing/03-make_epochs.py, scripts/preprocessing/04a-run_ica.py, scripts/preprocessing/04b-run_ssp.py, scripts/preprocessing/05a-apply_ica.py, scripts/preprocessing/05b-apply_ssp.py, scripts/preprocessing/06-ptp_reject.py, scripts/report/01-make_reports.py, scripts/sensor/01-make_evoked.py, scripts/sensor/02-sliding_estimator.py, scripts/sensor/03-time_frequency.py, scripts/sensor/04-group_average.py, scripts/source/01-make_bem_surfaces.py, scripts/source/02-make_forward.py, scripts/source/03-make_cov.py, scripts/source/04-make_inverse.py, scripts/source/05-group_average.py, tests/configs/config_ds000248.py
=> Add per-script configuration objects

config.py, docs/mkdocs.yml, docs/source/changes.md, docs/source/settings/preprocessing/breaks.md, scripts/preprocessing/01-maxfilter.py, scripts/preprocessing/02-frequency_filter.py, tests/configs/config_ERP_CORE.py, tests/configs/config_ds000246.py
=> ENH: Add automated break annotation

scripts/report/01-make_reports.py
MNE's implementation in Report.parse_folder() is much
nicer and more useful now. This also removed redundancy.
=> Disable our custom coreg plot

.circleci/config.yml, config.py, docs/mkdocs.yml, docs/source/changes.md, docs/source/examples/gen_examples.py, docs/source/settings/source/bem.md, scripts/report/01-make_reports.py, scripts/source/01-make_bem_surfaces.py, scripts/source/02-make_forward.py, scripts/source/05-group_average.py, tests/configs/config_ds000248.py, tests/configs/config_ds000248_no_mri.py, tests/datasets.py, tests/run_tests.py
=> Allow using fsaverage as a template MRI, e.g. for EEG studies without MR scans

config.py, docs/source/changes.md
=> Disable break detection by default

config.py, docs/source/changes.md, scripts/preprocessing/04b-run_ssp.py
=> ENH: add autoreject logic to SSP

config.py, docs/source/changes.md
=> When retrieving BIDS entity values, limit query to the data type we're actually processing

config.py, docs/source/changes.md, tests/configs/config_ERP_CORE.py
let's see how it goes -- added it to one of the ERP core configs @agramfort @hoechenberger
=> ENH: allow for custom montage in config file

config.py, docs/source/changes.md
=> Fix performance regressions

docs/source/changes.md, scripts/init/00-init_derivatives_dir.py, scripts/preprocessing/02-frequency_filter.py, scripts/preprocessing/03-make_epochs.py, scripts/preprocessing/04a-run_ica.py, scripts/preprocessing/04b-run_ssp.py, scripts/preprocessing/06-ptp_reject.py
It all began with the 06-ptp docstring which was obviously wrong.
=> docstrings

config.py, docs/source/settings/preprocessing/epochs.md, docs/source/settings/preprocessing/ssp_ica.md
=> Fix doc build

scripts/freesurfer/recon_all.py
=> use subjects_dir from config in freesurfer step

tests/configs/config_ds000247.py, tests/datasets.py, tests/ds000247_scans.tsv, tests/run_tests.py
Dataset has been updated upstream on OpenNeuro and the old paths don't exist anymore.
=> Update download paths for ds000247

tests/configs/config_ds000117.py, tests/datasets.py
@agramfort this should replicate the issue with
MNE-BIDS you're seeing.
=> Download all required sidecars for ds000117 tests

docs/source/changes.md, scripts/preprocessing/03-make_epochs.py, scripts/preprocessing/04a-run_ica.py, scripts/report/01-make_reports.py, scripts/sensor/04-group_average.py
=> fixes for EEG processing of ds117

config.py, docs/source/changes.md, run.py, scripts/freesurfer/recon_all.py, scripts/init/00-init_derivatives_dir.py, scripts/preprocessing/01-maxfilter.py, scripts/preprocessing/02-frequency_filter.py, scripts/preprocessing/03-make_epochs.py, scripts/preprocessing/04a-run_ica.py, scripts/preprocessing/04b-run_ssp.py, scripts/preprocessing/05a-apply_ica.py, scripts/preprocessing/05b-apply_ssp.py, scripts/preprocessing/06-ptp_reject.py, scripts/report/01-make_reports.py, scripts/sensor/01-make_evoked.py, scripts/sensor/02-sliding_estimator.py, scripts/sensor/03-time_frequency.py, scripts/source/01-make_bem_surfaces.py, scripts/source/02-make_forward.py, scripts/source/03-make_cov.py, scripts/source/04-make_inverse.py, scripts/source/05-group_average.py, tests/run_tests.py
=> MRG: Add n_jobs command line argument

config.py, scripts/preprocessing/01-maxfilter.py, scripts/preprocessing/02-frequency_filter.py, scripts/sensor/02-sliding_estimator.py
=> some fixes when trying to process the MIND dataset

config.py
=> fix unprotected access to bids_root in config

docs/source/changes.md, scripts/source/02-make_forward.py
=> fix forward for CTF data

.circleci/config.yml, config.py, run.py, scripts/init/00-init_derivatives_dir.py, scripts/preprocessing/01-maxfilter.py, scripts/preprocessing/02-frequency_filter.py, scripts/preprocessing/03-make_epochs.py, scripts/preprocessing/04a-run_ica.py, scripts/preprocessing/04b-run_ssp.py, scripts/preprocessing/05a-apply_ica.py, scripts/preprocessing/05b-apply_ssp.py, scripts/preprocessing/06-ptp_reject.py, scripts/report/01-make_reports.py, scripts/sensor/01-make_evoked.py, scripts/sensor/02-sliding_estimator.py, scripts/sensor/03-time_frequency.py, scripts/sensor/04-group_average.py, scripts/source/01-make_bem_surfaces.py, scripts/source/02-make_forward.py, scripts/source/03-make_cov.py, scripts/source/04-make_inverse.py, scripts/source/05-group_average.py, tests/requirements.txt
@hoechenberger I would love your input on this one
=> WIP : Storing processing logs and failures in excel file

.circleci/config.yml, .circleci/setup_bash.sh
=> MAINT: Only build with circle full

scripts/report/01-make_reports.py
=> pyvista was renamed to pyvistaqt

scripts/report/01-make_reports.py
=> test [circle ds000248]

.circleci/config.yml, docs/source/changes.md, scripts/preprocessing/03-make_epochs.py, tests/requirements.txt
cc @dengemann 
let's see if it makes CIs happy
=> Only assemble epochs for the conditions of interest if specified

.circleci/config.yml
=> Temporarily disable matchingpennies, ds000117

.circleci/config.yml
=> Re-enable ds000117 and matchingpennies [ds000117,eeg_matchingpennies]

config.py, scripts/preprocessing/01-maxfilter.py, scripts/preprocessing/02-frequency_filter.py
=> Adjustments for MNE-Python main dev branch

config.py, docs/source/changes.md
=> Don't parallelize if interactive=True

config.py, tests/configs/config_ds001810.py, tests/datasets.py
=> More testing with multi-session data [ci ds001810]

docs/source/changes.md, scripts/report/_01_make_reports.py
=> Fix ICA overlay plots in report

docs/source/changes.md, run.py, scripts/report/_01_make_reports.py
Preprocessing bits of the report step, tested with one participant of the TIWM data:
```
old: 262 sec
new: 106 sec
```
=> Speed up preprocessing report generation

scripts/report/_01_make_reports.py
=> Better logging during sensor-space report generation

scripts/report/_01_make_reports.py, scripts/sensor/_01_make_evoked.py, scripts/sensor/_04_group_average.py
Seems we forgot to add them back when transitioning to the new reports!
=> Add coregistration plots to reports

scripts/source/_02_make_forward.py
Looks like the forward solution failsafe routine needs a better check for existing coregistration `trans.fif` file(s)
=> Forward solution routine

scripts/source/_03_make_cov.py, scripts/source/_04_make_inverse.py
This is more like it!
@hoechenberger
=> Additional deriv overwrites

config.py, docs/source/changes.md, scripts/report/_01_make_reports.py
=> Use Agg Matplotlib backend in non-interactive mode

config.py, docs/source/changes.md, docs/source/settings/preprocessing/epochs.md, scripts/preprocessing/_03_make_epochs.py
This is a rework of #495 after discussion with @agramfort
=> Allow epochs selection based on a metadata query

scripts/report/_01_make_reports.py
cc @SophieHerbst @hoechenberger
=> fix : missing epochs.drop_bad(cfg.ica_reject)

scripts/source/_05_group_average.py
=> Don't run source group average if run_source_estimation is False

.circleci/config.yml, docs/build-docs.sh, requirements.txt, tests/requirements.txt
=> remove venv, dask diagnostic, don't duplicate req content in two files

docs/mkdocs.yml, tests/configs/config_eeg_matchingpennies.py
follow up to #508 
the tests only caught this after the pr was merged ... maybe some caching thing.
=> [test] fix conditions matchingpennies

requirements.txt
=> Try to fix build with upstream MNE changes

requirements.txt
=> use autoreject master

.circleci/setup_bash.sh, tests/download_test_data.py
=> Disable fancy 3D rendering options

config.py, docs/source/settings/source/bem.md, scripts/source/_01_make_bem_surfaces.py, scripts/source/_02_make_forward.py
=> make use_template_mri a string and add adjust_coreg parameter

docs/source/changes.md, scripts/preprocessing/_03_make_epochs.py
=> Restore accidentally reverted PR due to erroneous force-push to main

config.py, docs/source/changes.md, scripts/report/_01_make_reports.py, scripts/source/_03_make_cov.py, scripts/source/_04_make_inverse.py, tests/configs/config_ds000248.py
=> Allow using custom noise covariance matrices

docs/source/changes.md, scripts/report/_01_make_reports.py
=> Add configuration and system info to the reports

config.py, docs/source/changes.md, scripts/preprocessing/_01_maxfilter.py, scripts/preprocessing/_02_frequency_filter.py, scripts/preprocessing/_03_make_epochs.py, scripts/preprocessing/_04a_run_ica.py, scripts/preprocessing/_04b_run_ssp.py, scripts/preprocessing/_05a_apply_ica.py, scripts/preprocessing/_05b_apply_ssp.py, scripts/preprocessing/_06_ptp_reject.py, scripts/report/_01_make_reports.py, scripts/sensor/_01_make_evoked.py, scripts/sensor/_03_time_frequency.py, scripts/sensor/_04_group_average.py, scripts/source/_03_make_cov.py, tests/configs/config_ds000117.py, tests/run_tests.py
cc @agramfort
Let's see how this flies
=> Parallelize Maxwell filter across runs; use maxwell_filter_prepare_emptyroom()

config.py, docs/source/changes.md
=> Correct hardcoded lowpass filter on raw data.

config.py, scripts/preprocessing/_01_maxfilter.py, scripts/preprocessing/_02_frequency_filter.py
=> remove the save parameter that was not used

config.py, scripts/report/_01_make_reports.py
=> Fix error logging for Python <3.10, and avoid using deprecated NumPy function

.circleci/config.yml, docs/mkdocs.yml, docs/source/changes.md, tests/configs/config_ds004229.py, tests/datasets.py, tests/run_tests.py
Locally `python tests/run_tests.py --download=1 ds004229` works, let's see if CircleCI agrees!
https://openneuro.org/datasets/ds004229/
=> MAINT: Add infant dataset

.circleci/config.yml, .circleci/setup_bash.sh, Makefile, docs/source/getting_started/freesurfer.md, setup.cfg
=> Run all CircleCI jobs by default

.github/workflows/run-tests.yml, config.py, docs/source/changes.md, docs/source/settings/general.md, docs/source/settings/preprocessing/epochs.md, docs/source/settings/preprocessing/filter.md, docs/source/settings/source/inverse.md, scripts/source/_04_make_inverse.py, tests/test_documented.py
Toward #590, let's see if the parameters are auto-documented. If so, then there is probably no need for #590. If not, then I'll add a test that fails, then fix it.
=> ENH: Reenable loose and depth

config.py, docs/source/changes.md, docs/source/settings/sensor/statistics.md, scripts/report/_01_make_reports.py, scripts/sensor/_03_decoding_time_by_time.py, scripts/sensor/_99_group_average.py, tests/configs/config_ERP_CORE.py, tests/configs/config_ds000246.py, tests/configs/config_ds003392.py
=> ENH: Allow decim of GAT

config.py, tests/configs/config_ERP_CORE.py, tests/configs/config_ds000246.py, tests/configs/config_ds001971.py
Closes #548
TDD, first let's see the failure.
No need for changelog update I think because it wasn't updated when dask was disabled, either.
=> MAINT: Reenable dask

config.py, docs/source/changes.md, scripts/preprocessing/_01_maxfilter.py, scripts/preprocessing/_02_frequency_filter.py, scripts/preprocessing/_03_make_epochs.py, scripts/preprocessing/_04a_run_ica.py, scripts/preprocessing/_04b_run_ssp.py, scripts/preprocessing/_05a_apply_ica.py, scripts/preprocessing/_05b_apply_ssp.py, scripts/preprocessing/_06_ptp_reject.py, scripts/sensor/_01_make_evoked.py, scripts/sensor/_02_decoding_full_epochs.py, scripts/sensor/_03_decoding_time_by_time.py, scripts/sensor/_04_time_frequency.py
=> ENH: More caching and fixes

config.py
=> Set on_missing parameter of raw.drop_channels to warn by default.

.circleci/config.yml, config.py, docs/build-docs.sh, docs/mkdocs.yml, docs/source/changes.md, docs/source/examples/gen_examples.py, scripts/preprocessing/_04b_run_ssp.py, scripts/preprocessing/_05b_apply_ssp.py, scripts/preprocessing/_06_ptp_reject.py, scripts/report/_01_make_reports.py, tests/configs/config_ds003775.py, tests/test_documented.py
Locally at least it produces something reasonable:
=> ENH: Add SSP joint plots to reports

docs/source/getting_started/basic_usage.md, docs/source/getting_started/freesurfer.md, docs/source/getting_started/install.md
=> Update installation & usage documentation

mne_bids_pipeline/_import_data.py, mne_bids_pipeline/_run.py, mne_bids_pipeline/scripts/preprocessing/_01_maxfilter.py
found the problem when running the new CSP code on @SophieHerbst data @hoechenberger 
Once merge I'll report next on the CSP pull request.
=> rest does not have the run information and has no events to fix

mne_bids_pipeline/tests/configs/config_ERP_CORE.py
=> fix typo in tmin

mne_bids_pipeline/scripts/init/_01_find_empty_room.py
Small bugfix for no new feature so no `changes.md` update necessary I think
Gets rid of a TODO involving sidecars, hooray!
=> BUG: Fix bug with empty-room matching message

docs/source/changes.md, mne_bids_pipeline/_run.py
=> BUG: Add hashing of sidecar files

docs/source/changes.md, docs/source/examples/gen_examples.py, docs/source/settings/general.md, mne_bids_pipeline/_config.py, mne_bids_pipeline/_config_import.py, mne_bids_pipeline/_main.py, mne_bids_pipeline/steps/sensor/_06_make_cov.py, mne_bids_pipeline/steps/source/_04_make_forward.py, mne_bids_pipeline/tests/test_documented.py, mne_bids_pipeline/tests/test_validation.py
=> ENH: Add misspelling check

docs/source/settings/sensor/statistics.md, mne_bids_pipeline/_config.py, mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py, pyproject.toml
=> add decode_epochs_tmin and decode_epochs_tmax params

docs/source/getting_started/install.md, mne_bids_pipeline/_report.py, mne_bids_pipeline/steps/sensor/_99_group_average.py, pyproject.toml
Requires https://github.com/mne-tools/mne-python/pull/11346, so the URL is changed here. Will revert once that PR is merged.
Also updated the installation instructions in prep for release.
Closes #637
Closes #669
=> BUG: Fix bug with report generation

docs/source/changes.md, mne_bids_pipeline/_config_import.py, mne_bids_pipeline/tests/test_validation.py
More validation -- look for at least one removed name.
@hoechenberger there are probably lots of others to add here. Feel free to push directly based on memory if you want, or you can do it in a follow-up PR. This one just adds `debug`->`on_error='debug'`.
=> ENH: Check for removed names

pyproject.toml
@hoechenberger feel free to mark for merge if you're happy
=> MAINT: Add setuptools dep

README.md, docs/hooks.py, docs/mkdocs.yml, docs/source/index.md, pyproject.toml
Help with #684.
Short of updating all structure since @hoechenberger is working on that, this just:
1. Makes sure we use consistent taglines across PyPI and our homepage
2. Adds a "last updated" to the footer
3. Fixes the `overrides` so that the banner hopefully works
Committed with `[circle ds003392]` to speed up the doc build
=> MAINT: Fix bug with overrides

.circleci/config.yml
Fixes something I think I broke -- datalad needs an email 
https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/3595/workflows/5821b114-06f0-4502-9bca-908ee41db6dc/jobs/42580
=> FIX: git setup

docs/source/settings/general.md, docs/source/v1.1.md.inc, mne_bids_pipeline/_config.py, mne_bids_pipeline/_config_import.py, mne_bids_pipeline/_main.py, mne_bids_pipeline/_parallel.py, mne_bids_pipeline/steps/sensor/_03_decoding_time_by_time.py, mne_bids_pipeline/tests/configs/config_ERP_CORE.py, mne_bids_pipeline/tests/configs/config_ds000246.py, mne_bids_pipeline/tests/configs/config_ds000248_base.py, mne_bids_pipeline/tests/configs/config_ds003775.py
=> MAINT: Fix N_JOBS to n_jobs

docs/source/v1.0.md.inc, docs/source/v1.1.md.inc, mne_bids_pipeline/tests/conftest.py
Hopefully last PR before 1.0.3 release, just moving stuff from v1.1 to v1.0.3 and updating the date
=> DOC: Document as 1.0.3

docs/hooks.py, docs/source/index.md
=> FIX: Dedup

docs/source/settings/preprocessing/filter.md, docs/source/v1.1.md.inc, mne_bids_pipeline/_config.py, mne_bids_pipeline/steps/preprocessing/_03_frequency_filter.py, mne_bids_pipeline/tests/configs/config_ERP_CORE.py, mne_bids_pipeline/tests/test_documented.py
=> Add notch filter

pyproject.toml
=> Bump required mkdocs-material version to ensure Twemojis work

.circleci/config.yml, mne_bids_pipeline/tests/conftest.py
Pure CI change so no changelog entry I think
For https://github.com/mne-tools/mne-python/issues/11532
=> MAINT: Use git

docs/source/v1.2.md.inc, mne_bids_pipeline/_config_utils.py
=> Caching mne.get_datatypes to speed up _get_ignore_datatypes

docs/source/v1.3.md.inc, mne_bids_pipeline/_report.py, mne_bids_pipeline/_run.py
=> BUG: Fix bug with sys info addition

docs/source/v1.3.md.inc, mne_bids_pipeline/steps/sensor/_05_decoding_csp.py
=> Provide a more helpful log message if the CSP decoding step is being skipped

mne_bids_pipeline/tests/conftest.py
Tiny change that users will probably never see so I think no need for changelog update. I just hit it locally using some dev versions
=> MAINT: Deal with h5py numpy compat

docs/source/changes.md, docs/source/v1.3.md.inc, docs/source/v1.4.md.inc, mne_bids_pipeline/_import_data.py, mne_bids_pipeline/steps/preprocessing/_01_data_quality.py, mne_bids_pipeline/tests/configs/config_ds000117.py, mne_bids_pipeline/tests/conftest.py
Closes #740
@allermat feel free to try this branch, hopefully it fixes your issue!
=> BUG: Fix bug with mf_reference_run

.pre-commit-config.yaml, docs/source/v1.5.md.inc
Hopefully this *does not* modify `freesurfer/contrib`!
=> MAINT: pre-commit.ci

docs/source/examples/gen_examples.py, docs/source/v1.5.md.inc, mne_bids_pipeline/_download.py, mne_bids_pipeline/tests/datasets.py, mne_bids_pipeline/tests/test_run.py, pyproject.toml
Uses `pooch` and DRYs out the code a bit along the way
Closes #771
=> MAINT: Use pooch for downloading web data

mne_bids_pipeline/steps/source/_05_make_inverse.py
Within-release bugfix for #765 so no need for `changes` update
=> BUG: Fix bug where individual invs were not rendered

mne_bids_pipeline/_report.py
Tiny change for deprecation warning here so I don't think changelog update is necessary
https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/3944/workflows/bbcc225b-e8b7-483a-b56b-f8c95a841996/jobs/51202
=> MAINT: Fix bug with item

.circleci/config.yml, docs/mkdocs.yml, docs/source/css/extra.css
=> Ensure link in  "You're not viewing the latest stable version" banner is readable in light and dark theme

docs/source/settings/sensor/mvpa.md, docs/source/v1.5.md.inc, mne_bids_pipeline/_config.py, mne_bids_pipeline/_config_utils.py, mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py, mne_bids_pipeline/steps/sensor/_03_decoding_time_by_time.py, mne_bids_pipeline/steps/sensor/_05_decoding_csp.py
=> Allow decoding using epochs at different stages of pre-processing

.circleci/config.yml, mne_bids_pipeline/tests/conftest.py
=> MAINT: Fix CIs

.circleci/config.yml, docs/source/v1.6.md.inc, mne_bids_pipeline/steps/preprocessing/_08a_apply_ica.py, mne_bids_pipeline/tests/conftest.py, mne_bids_pipeline/tests/test_run.py
Closes #852
@SophieHerbst feel free to try this
@hoechenberger rephrased the changelog a bit to match other sections but I can revert (or feel free to push a commit) if you want
=> BUG: Fix bug with split epochs and ICA

docs/source/v1.7.md.inc, mne_bids_pipeline/_run.py
=> Improve logging during cache invalidation

BUILDING.md, CONTRIBUTING.md, pyproject.toml
=> Update contributing instructions and remove outdated building instructions

docs/source/v1.6.md.inc, docs/source/v1.7.md.inc
=> Add missing release dates to changelog

docs/source/v1.9.md.inc, mne_bids_pipeline/_import_data.py, mne_bids_pipeline/_logging.py, mne_bids_pipeline/_report.py, mne_bids_pipeline/_run.py, mne_bids_pipeline/steps/init/_01_init_derivatives_dir.py, mne_bids_pipeline/steps/preprocessing/_01_data_quality.py, mne_bids_pipeline/steps/preprocessing/_04_frequency_filter.py, mne_bids_pipeline/steps/preprocessing/_05_regress_artifact.py, mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py, mne_bids_pipeline/steps/sensor/_05_decoding_csp.py, mne_bids_pipeline/steps/sensor/_06_make_cov.py, mne_bids_pipeline/steps/sensor/_99_group_average.py, mne_bids_pipeline/tests/test_functions.py
=> MAINT: Ensure input changes cause output changes

.circleci/config.yml
=> Try to fix documentation deployment

docs/source/v1.9.md.inc, mne_bids_pipeline/steps/preprocessing/_06a2_find_ica_artifacts.py, mne_bids_pipeline/steps/preprocessing/_08a_apply_ica.py, mne_bids_pipeline/tests/conftest.py
=> Improve logging during ICA artifact discovery and rejection

.git_archival.txt
=> remove ref-names from .git_archival.txt

docs/source/examples/gen_examples.py, docs/source/v1.9.md.inc, mne_bids_pipeline/_config_template.py, mne_bids_pipeline/_config_utils.py, mne_bids_pipeline/_import_data.py, mne_bids_pipeline/_parallel.py, mne_bids_pipeline/_report.py, mne_bids_pipeline/_run.py, mne_bids_pipeline/steps/preprocessing/_04_frequency_filter.py, mne_bids_pipeline/steps/sensor/_02_decoding_full_epochs.py, mne_bids_pipeline/steps/sensor/_05_decoding_csp.py
Noticed one of these, figured I might as well fix all occurrences
=> fix split strings (presumably from autoformatter)

docs/source/v1.10.md.inc, docs/source/v1.9.md.inc, mne_bids_pipeline/_config_utils.py, mne_bids_pipeline/steps/freesurfer/_01_recon_all.py, mne_bids_pipeline/steps/freesurfer/_02_coreg_surfaces.py, mne_bids_pipeline/steps/source/_01_make_bem_surfaces.py, mne_bids_pipeline/steps/source/_02_make_bem_solution.py, mne_bids_pipeline/steps/source/_03_setup_source_space.py, mne_bids_pipeline/steps/source/_04_make_forward.py, mne_bids_pipeline/steps/source/_05_make_inverse.py, mne_bids_pipeline/steps/source/_99_group_average.py
WIP. Could use some advice about the best approach here; so far it *should* work (but yet untested!) for my use case but definitely won't work for the "normal" case that is currently supported on `main`. See the (small) diff for a prominent comment explaining the issue.
=> Allow separate MRIs per session (for longitudinal studies)

docs/source/getting_started/freesurfer.md, docs/source/v1.10.md.inc
=> document need for xvfb/osmesa on headless

docs/source/v1.10.md.inc, mne_bids_pipeline/steps/sensor/_06_make_cov.py
=> FIX: noise_cov_method for raw as well

docs/source/dev.md.inc, mne_bids_pipeline/_config.py, mne_bids_pipeline/_config_import.py, mne_bids_pipeline/steps/preprocessing/_03_maxfilter.py, mne_bids_pipeline/tests/configs/config_ds003392.py, mne_bids_pipeline/tests/test_validation.py
=> add config for passing extra kwargs to maxwell_filter

docs/source/dev.md.inc, ignore_words.txt, mne_bids_pipeline/_config_import.py
=> validate extra_config

.circleci/run_dataset_and_copy_files.sh, .circleci/setup_bash.sh, .github/workflows/tests.yml
No need for changelog update. Will require updating merge reqs because it splits the caching test into two steps. More DRY and should overall complete a bit faster even though there is more `pip` overhead.
Just for fun I'm going to try adding an `arm` run and we can see what breaks. Then I'll remove :)
Ready for review/merge in the meantime
=> MAINT: Refactor and document CIs better

docs/source/dev.md.inc, mne_bids_pipeline/steps/source/_04_make_forward.py
=> raise error if loaded SourceSpaces has unexpected subject

docs/source/dev.md.inc, mne_bids_pipeline/_config.py, mne_bids_pipeline/_config_import.py, mne_bids_pipeline/_config_utils.py, mne_bids_pipeline/steps/preprocessing/_06b_run_ssp.py, mne_bids_pipeline/tests/configs/config_MNE_funloc_data.py, mne_bids_pipeline/tests/test_validation.py
=> allow dict for ssp_ecg_channel

.github/workflows/tests.yml, mne_bids_pipeline/_config_import.py, mne_bids_pipeline/_download.py, mne_bids_pipeline/tests/conftest.py, mne_bids_pipeline/tests/datasets.py, pyproject.toml
fixes https://github.com/mne-tools/mne-bids-pipeline/pull/1062#issuecomment-2775830266
within-cycle bugfix so no changelog needed.
Closes #1063
=> avoid backslash in fstring and frontload fsaverage download
